-- All these inserts are examples. You have to insert the data that you required

-- SURVEY TYPES

Insert into TB_LIS_SURVEY_TYPES (ID,IDENTIFIER,UUID,VERSION) values (FILL_WITH_SCHEMA_NAME.GetSequenceNextValue('SURVEY_TYPES'),'COYUNTURAL','f5895f76-14ae-47d2-b228-f4e977833be7',0);
UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'SURVEY_TYPES';

Insert into TB_LIS_SURVEY_TYPES (ID,IDENTIFIER,UUID,VERSION) values (FILL_WITH_SCHEMA_NAME.GetSequenceNextValue('SURVEY_TYPES'),'ESTRUCTURAL','aaaaaaaa-14ae-47d2-b228-f4e977833be7',0);
UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'SURVEY_TYPES';

Insert into TB_LIS_SURVEY_TYPES (ID,IDENTIFIER,UUID,VERSION) values (FILL_WITH_SCHEMA_NAME.GetSequenceNextValue('SURVEY_TYPES'),'OTRAS','afaaaaaa-14ae-47d2-b228-f4e977833be7',0);
UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'SURVEY_TYPES';

-- INSTANCE TYPES

Insert into TB_LIS_INSTANCE_TYPES (ID,IDENTIFIER,UUID,VERSION) values (FILL_WITH_SCHEMA_NAME.GetSequenceNextValue('INSTANCE_TYPES'),'SERIE','bbbbbbbb-14ae-47d2-b228-f4e977833be7',0);
UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'INSTANCE_TYPES';

Insert into TB_LIS_INSTANCE_TYPES (ID,IDENTIFIER,UUID,VERSION) values (FILL_WITH_SCHEMA_NAME.GetSequenceNextValue('INSTANCE_TYPES'),'SECCION','cccccccc-14ae-47d2-b228-f4e977833be7',0);
UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'INSTANCE_TYPES';

-- COLL METHODS

Insert into TB_LIS_COLL_METHODS (ID,IDENTIFIER,UUID,VERSION) values (FILL_WITH_SCHEMA_NAME.GetSequenceNextValue('COLL_METHODS'),'AUTOENUMERACION','dddddddd-14ae-47d2-b228-f4e977833be7',0);
UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'COLL_METHODS';

Insert into TB_LIS_COLL_METHODS (ID,IDENTIFIER,UUID,VERSION) values (FILL_WITH_SCHEMA_NAME.GetSequenceNextValue('COLL_METHODS'),'ENTREVISTA_DIRECTA','egeeeeee-14ae-47d2-b228-f4e977833be7',0);
UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'COLL_METHODS';

Insert into TB_LIS_COLL_METHODS (ID,IDENTIFIER,UUID,VERSION) values (FILL_WITH_SCHEMA_NAME.GetSequenceNextValue('COLL_METHODS'),'CONVERSACION_TELEFONO','eeeeehee-14ae-47d2-b228-f4e977833be7',0);
UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'COLL_METHODS';

Insert into TB_LIS_COLL_METHODS (ID,IDENTIFIER,UUID,VERSION) values (FILL_WITH_SCHEMA_NAME.GetSequenceNextValue('COLL_METHODS'),'TRANSCRIPCION_DOCUMENTO','eeereeee-14ae-47d2-b228-f4e977833be7',0);
UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'COLL_METHODS';

Insert into TB_LIS_COLL_METHODS (ID,IDENTIFIER,UUID,VERSION) values (FILL_WITH_SCHEMA_NAME.GetSequenceNextValue('COLL_METHODS'),'OBSERVACION_DIRECTA','edeeeeee-14ae-47d2-b228-f4e977833be7',0);
UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'COLL_METHODS';

Insert into TB_LIS_COLL_METHODS (ID,IDENTIFIER,UUID,VERSION) values (FILL_WITH_SCHEMA_NAME.GetSequenceNextValue('COLL_METHODS'),'FORMAS_MIXTAS','ee4eeeee-14ae-47d2-b228-f4e977833be7',0);
UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'COLL_METHODS';

Insert into TB_LIS_COLL_METHODS (ID,IDENTIFIER,UUID,VERSION) values (FILL_WITH_SCHEMA_NAME.GetSequenceNextValue('COLL_METHODS'),'OTRAS','7eeeeeee-14ae-47d2-b228-f4e977833be7',0);
UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'COLL_METHODS';

Insert into TB_LIS_COLL_METHODS (ID,IDENTIFIER,UUID,VERSION) values (FILL_WITH_SCHEMA_NAME.GetSequenceNextValue('COLL_METHODS'),'NO_APLICABLE','eee9eeee-14ae-47d2-b228-f4e977833be7',0);
UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'COLL_METHODS';

Insert into TB_LIS_COLL_METHODS (ID,IDENTIFIER,UUID,VERSION) values (FILL_WITH_SCHEMA_NAME.GetSequenceNextValue('COLL_METHODS'),'INDETERMINADA','eee89eee-14ae-47d2-b228-f4e977833be7',0);
UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'COLL_METHODS';


-- COSTS

Insert into TB_LIS_COSTS (ID,IDENTIFIER,UUID,VERSION) values (FILL_WITH_SCHEMA_NAME.GetSequenceNextValue('COSTS'),'ESTIMADO','ffffffff-14ae-47d2-b228-f4e977833be7',0);
UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'COSTS';

Insert into TB_LIS_COSTS (ID,IDENTIFIER,UUID,VERSION) values (FILL_WITH_SCHEMA_NAME.GetSequenceNextValue('COSTS'),'NO_CALCULADO','gggggggg-14ae-47d2-b228-f4e977833be7',0);
UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'COSTS';

-- SURVEY SOURCES

Insert into TB_LIS_SURVEY_SOURCES (ID,IDENTIFIER,UUID,VERSION) values (FILL_WITH_SCHEMA_NAME.GetSequenceNextValue('SURVEY_SOURCES'),'ENCUESTA','hhhhhhhh-14ae-47d2-b228-f4e977833be7',0);
UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'SURVEY_SOURCES';

Insert into TB_LIS_SURVEY_SOURCES (ID,IDENTIFIER,UUID,VERSION) values (FILL_WITH_SCHEMA_NAME.GetSequenceNextValue('SURVEY_SOURCES'),'ADMINISTRACION','iiiiiiii-14ae-47d2-b228-f4e977833be7',0);
UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'SURVEY_SOURCES';

-- OFFICIALITY TYPES

Insert into TB_LIS_OFFICIALITY_TYPES (ID,IDENTIFIER,UUID,VERSION) values (FILL_WITH_SCHEMA_NAME.GetSequenceNextValue('OFFICIALITY_TYPES'),'ESTUDIO','jjjjjjjj-14ae-47d2-b228-f4e977833be7',0);
UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'OFFICIALITY_TYPES';

Insert into TB_LIS_OFFICIALITY_TYPES (ID,IDENTIFIER,UUID,VERSION) values (FILL_WITH_SCHEMA_NAME.GetSequenceNextValue('OFFICIALITY_TYPES'),'OFICIAL','kkkkkkkk-14ae-47d2-b228-f4e977833be7',0);
UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'OFFICIALITY_TYPES';

