-- ---------------------------------------------------------------------------------------------------
-- METAMAC-2215 - [BBDD] Las constraints no pueden ser DEFERRED porque no hay soporte para SQLServer
-- ---------------------------------------------------------------------------------------------------

ALTER TABLE TB_FAMILIES DROP CONSTRAINT FAMILIES_CODE;
ALTER TABLE TB_OPERATIONS DROP CONSTRAINT OPERATIONS_CODE;
ALTER TABLE TB_INSTANCES DROP CONSTRAINT INSTANCES_CODE;
ALTER TABLE TB_LOCALISED_STRINGS DROP CONSTRAINT LOCALE_INTERNATIONAL;

ALTER TABLE TB_FAMILIES ADD CONSTRAINT FAMILIES_CODE UNIQUE(CODE);
ALTER TABLE TB_OPERATIONS ADD CONSTRAINT OPERATIONS_CODE UNIQUE(CODE);
ALTER TABLE TB_INSTANCES ADD CONSTRAINT INSTANCES_CODE UNIQUE(CODE);
ALTER TABLE TB_LOCALISED_STRINGS ADD CONSTRAINT LOCALE_INTERNATIONAL UNIQUE(LOCALE, INTERNATIONAL_STRING_FK);

commit;