-- Create normal entities
    
CREATE TABLE TBL_INTERNATIONAL_STRINGS (
  ID NUMBER(19) NOT NULL,
  VERSION NUMBER(19) NOT NULL
);


CREATE TABLE LIS_COLL_METHODS (
  ID NUMBER(19) NOT NULL,
  IDENTIFIER VARCHAR2(100) NOT NULL,
  UUID VARCHAR2(36) NOT NULL,
  VERSION NUMBER(19) NOT NULL,
  DESCRIPTION NUMBER(19)
);


CREATE TABLE LIS_COSTS (
  ID NUMBER(19) NOT NULL,
  IDENTIFIER VARCHAR2(100) NOT NULL,
  UUID VARCHAR2(36) NOT NULL,
  VERSION NUMBER(19) NOT NULL,
  DESCRIPTION NUMBER(19)
);


CREATE TABLE TBL_FAMILIES (
  ID NUMBER(19) NOT NULL,
  CODE VARCHAR2(100) NOT NULL,
  URI VARCHAR2(100),
  INTERNAL_INVENTORY_DATE_TZ VARCHAR2(50)
  ,
  INTERNAL_INVENTORY_DATE TIMESTAMP ,
  INVENTORY_DATE_TZ VARCHAR2(50)
  ,
  INVENTORY_DATE TIMESTAMP ,
  UUID VARCHAR2(36) NOT NULL,
  CREATED_DATE_TZ VARCHAR2(50)
  ,
  CREATED_DATE TIMESTAMP,
  CREATED_BY VARCHAR2(50),
  LAST_UPDATED_TZ VARCHAR2(50)
  ,
  LAST_UPDATED TIMESTAMP,
  LAST_UPDATED_BY VARCHAR2(50),
  VERSION NUMBER(19) NOT NULL,
  TITLE_FK NUMBER(19) NOT NULL,
  ACRONYM_FK NUMBER(19),
  DESCRIPTION_FK NUMBER(19),
  PROC_STATUS VARCHAR2(40) NOT NULL
);


CREATE TABLE LIS_SURVEY_TYPES (
  ID NUMBER(19) NOT NULL,
  IDENTIFIER VARCHAR2(100) NOT NULL,
  UUID VARCHAR2(36) NOT NULL,
  VERSION NUMBER(19) NOT NULL,
  DESCRIPTION NUMBER(19)
);


CREATE TABLE LIS_OFFICIALITY_TYPES (
  ID NUMBER(19) NOT NULL,
  IDENTIFIER VARCHAR2(100) NOT NULL,
  UUID VARCHAR2(36) NOT NULL,
  VERSION NUMBER(19) NOT NULL,
  DESCRIPTION NUMBER(19)
);


CREATE TABLE TBL_OPERATIONS (
  ID NUMBER(19) NOT NULL,
  CODE VARCHAR2(100) NOT NULL,
  URI VARCHAR2(100),
  INDICATOR_SYSTEM NUMBER(1,0) NOT NULL,
  INTERNAL_INVENTORY_DATE_TZ VARCHAR2(50)
  ,
  INTERNAL_INVENTORY_DATE TIMESTAMP ,
  CURRENTLY_ACTIVE NUMBER(1,0) NOT NULL,
  REL_POL_US_AC_URL VARCHAR2(100),
  RELEASE_CALENDAR NUMBER(1,0) NOT NULL,
  RELEASE_CALENDAR_ACCESS VARCHAR2(100),
  INVENTORY_DATE_TZ VARCHAR2(50)
  ,
  INVENTORY_DATE TIMESTAMP ,
  REV_POLICY_URL VARCHAR2(100),
  REV_PRACTICE_URL VARCHAR2(100),
  COMMENT_URL VARCHAR2(100),
  NOTES_URL VARCHAR2(100),
  UUID VARCHAR2(36) NOT NULL,
  CREATED_DATE_TZ VARCHAR2(50)
  ,
  CREATED_DATE TIMESTAMP,
  CREATED_BY VARCHAR2(50),
  LAST_UPDATED_TZ VARCHAR2(50)
  ,
  LAST_UPDATED TIMESTAMP,
  LAST_UPDATED_BY VARCHAR2(50),
  VERSION NUMBER(19) NOT NULL,
  TITLE_FK NUMBER(19) NOT NULL,
  ACRONYM_FK NUMBER(19),
  OBJECTIVE_FK NUMBER(19),
  DESCRIPTION_FK NUMBER(19),
  SURVEY_TYPE_FK NUMBER(19),
  OFFICIALITY_TYPE_FK NUMBER(19),
  REL_POL_US_AC_FK NUMBER(19),
  REV_POLICY_FK NUMBER(19),
  REV_PRACTICE_FK NUMBER(19),
  COMMENT_FK NUMBER(19),
  NOTES_FK NUMBER(19),
  COMMON_METADATA_URI_INT VARCHAR2(255),
  COMMON_METADATA_CODE_ID VARCHAR2(255),
  COMMON_METADATA_TYPE VARCHAR2(40),
  SUBJECT_AREA_URI_INT VARCHAR2(255),
  SUBJECT_AREA_CODE_ID VARCHAR2(255),
  SUBJECT_AREA_TYPE VARCHAR2(40),
  PROC_STATUS VARCHAR2(40) NOT NULL,
  STATUS VARCHAR2(40) NOT NULL
);


CREATE TABLE LIS_INSTANCE_TYPES (
  ID NUMBER(19) NOT NULL,
  IDENTIFIER VARCHAR2(100) NOT NULL,
  UUID VARCHAR2(36) NOT NULL,
  VERSION NUMBER(19) NOT NULL,
  DESCRIPTION NUMBER(19)
);


CREATE TABLE LIS_SURVEY_SOURCES (
  ID NUMBER(19) NOT NULL,
  IDENTIFIER VARCHAR2(100) NOT NULL,
  UUID VARCHAR2(36) NOT NULL,
  VERSION NUMBER(19) NOT NULL,
  DESCRIPTION NUMBER(19)
);


CREATE TABLE TBL_INSTANCES (
  ID NUMBER(19) NOT NULL,
  ORDER_IDX NUMBER(10) NOT NULL,
  CODE VARCHAR2(100) NOT NULL,
  URI VARCHAR2(100),
  INTERNAL_INVENTORY_DATE_TZ VARCHAR2(50)
  ,
  INTERNAL_INVENTORY_DATE TIMESTAMP ,
  DOC_METHOD_URL VARCHAR2(100),
  DATA_VALIDATION_URL VARCHAR2(100),
  DATA_COMPILATION_URL VARCHAR2(100),
  ADJUSTMENT_URL VARCHAR2(100),
  COST_BURDEN_URL VARCHAR2(100),
  INVENTORY_DATE_TZ VARCHAR2(50)
  ,
  INVENTORY_DATE TIMESTAMP ,
  QUALITY_DOC_URL VARCHAR2(100),
  QUALITY_ASSURE_URL VARCHAR2(100),
  QUALITY_ASSMNT_URL VARCHAR2(100),
  USER_NEEDS_URL VARCHAR2(100),
  USER_SAT_URL VARCHAR2(100),
  COMPLETENESS_URL VARCHAR2(100),
  TIMELINESS_URL VARCHAR2(100),
  PUNCTUALITY_URL VARCHAR2(100),
  ACCURACY_OVERALL_URL VARCHAR2(100),
  SAMPLING_ERR_URL VARCHAR2(100),
  NONSAMPLING_ERR_URL VARCHAR2(100),
  COHER_X_DOMAIN_URL VARCHAR2(100),
  COHER_INTERNAL_URL VARCHAR2(100),
  COMMENT_URL VARCHAR2(100),
  NOTES_URL VARCHAR2(100),
  UUID VARCHAR2(36) NOT NULL,
  CREATED_DATE_TZ VARCHAR2(50)
  ,
  CREATED_DATE TIMESTAMP,
  CREATED_BY VARCHAR2(50),
  LAST_UPDATED_TZ VARCHAR2(50)
  ,
  LAST_UPDATED TIMESTAMP,
  LAST_UPDATED_BY VARCHAR2(50),
  VERSION NUMBER(19) NOT NULL,
  TITLE_FK NUMBER(19) NOT NULL,
  ACRONYM_FK NUMBER(19),
  OPERATION_FK NUMBER(19) NOT NULL,
  DATA_DESCRIPTION_FK NUMBER(19),
  STATISTICAL_POPULATION_FK NUMBER(19),
  GEOGRAPHIC_COMPARABILITY_FK NUMBER(19),
  TEMPORAL_COMPARABILITY_FK NUMBER(19),
  STAT_CONC_DEF_FK NUMBER(19),
  CLASS_SYSTEM_FK NUMBER(19),
  INSTANCE_TYPE_FK NUMBER(19),
  DOC_METHOD_FK NUMBER(19),
  SURVEY_SOURCE_FK NUMBER(19),
  COLL_METHOD_FK NUMBER(19),
  DATA_VALIDATION_FK NUMBER(19),
  DATA_COMPILATION_FK NUMBER(19),
  ADJUSTMENT_FK NUMBER(19),
  COST_BURDEN_FK NUMBER(19),
  QUALITY_DOC_FK NUMBER(19),
  QUALITY_ASSURE_FK NUMBER(19),
  QUALITY_ASSMNT_FK NUMBER(19),
  USER_NEEDS_FK NUMBER(19),
  USER_SAT_FK NUMBER(19),
  COMPLETENESS_FK NUMBER(19),
  TIMELINESS_FK NUMBER(19),
  PUNCTUALITY_FK NUMBER(19),
  ACCURACY_OVERALL_FK NUMBER(19),
  SAMPLING_ERR_FK NUMBER(19),
  NONSAMPLING_ERR_FK NUMBER(19),
  COHER_X_DOMAIN_FK NUMBER(19),
  COHER_INTERNAL_FK NUMBER(19),
  COMMENT_FK NUMBER(19),
  NOTES_FK NUMBER(19),
  GEOGRAPHIC_GRANULARITY_URI_INT VARCHAR2(255),
  GEOGRAPHIC_GRANULARITY_CODE_ID VARCHAR2(255),
  GEOGRAPHIC_GRANULARITY_TYPE VARCHAR2(40),
  TEMPORAL_GRANULARITY_URI_INT VARCHAR2(255),
  TEMPORAL_GRANULARITY_CODE_ID VARCHAR2(255),
  TEMPORAL_GRANULARITY_TYPE VARCHAR2(40),
  BASE_PERIOD_URI_INT VARCHAR2(255),
  BASE_PERIOD_CODE_ID VARCHAR2(255),
  BASE_PERIOD_TYPE VARCHAR2(40),
  PROC_STATUS VARCHAR2(40) NOT NULL
);


CREATE TABLE TBL_LOCALISED_STRINGS (
  ID NUMBER(19) NOT NULL,
  LABEL VARCHAR2(4000) NOT NULL,
  LOCALE VARCHAR2(100) NOT NULL,
  VERSION NUMBER(19) NOT NULL,
  INTERNATIONAL_STRING_FK NUMBER(19)
);


CREATE TABLE TBL_EXTERNAL_ITEMS (
  ID NUMBER(19) NOT NULL,
  UUID VARCHAR2(36) NOT NULL,
  EXT_URI_INT VARCHAR2(255) NOT NULL,
  EXT_CODE_ID VARCHAR2(255) NOT NULL,
  EXT_TYPE VARCHAR2(40) NOT NULL
);



-- Create many to many relations
    
CREATE TABLE TBL_EI_CLASS_SYSTEM_LISTS (
  CLASS_SYSTEM_LIST_FK NUMBER(19) NOT NULL,
  TBL_INSTANCES NUMBER(19) NOT NULL
);


CREATE TABLE TBL_EI_CONC_DEF_LISTS (
  STAT_CONC_DEF_LIST_FK NUMBER(19) NOT NULL,
  TBL_INSTANCES NUMBER(19) NOT NULL
);


CREATE TABLE TBL_EI_FREQ_COLL (
  FREQ_COLL_FK NUMBER(19) NOT NULL,
  TBL_INSTANCES NUMBER(19) NOT NULL
);


CREATE TABLE TBL_EI_INF_SUPPLIERS (
  INFORMATION_SUPPLIERS_FK NUMBER(19) NOT NULL,
  TBL_INSTANCES NUMBER(19) NOT NULL
);


CREATE TABLE TBL_EI_PRODUCERS (
  PRODUCER_FK NUMBER(19) NOT NULL,
  TBL_OPERATIONS NUMBER(19) NOT NULL
);


CREATE TABLE TBL_EI_PUBLISHERS (
  PUBLISHER_FK NUMBER(19) NOT NULL,
  TBL_OPERATIONS NUMBER(19) NOT NULL
);


CREATE TABLE TBL_EI_REG_CONTRIBUTORS (
  REGIONAL_CONTRIBUTOR_FK NUMBER(19) NOT NULL,
  TBL_OPERATIONS NUMBER(19) NOT NULL
);


CREATE TABLE TBL_EI_REG_RESPONSIBLES (
  REGIONAL_RESPONSIBLE_FK NUMBER(19) NOT NULL,
  TBL_OPERATIONS NUMBER(19) NOT NULL
);


CREATE TABLE TBL_EI_SECONDARY_AREAS (
  SECUN_SUBJECT_AREAS_FK NUMBER(19) NOT NULL,
  TBL_OPERATIONS NUMBER(19) NOT NULL
);


CREATE TABLE TBL_EI_STATISTICAL_UNITS (
  STATISTICAL_UNIT_FK NUMBER(19) NOT NULL,
  TBL_INSTANCES NUMBER(19) NOT NULL
);


CREATE TABLE TBL_EI_UNITS_MEASURE (
  UNIT_MEASURE_FK NUMBER(19) NOT NULL,
  TBL_INSTANCES NUMBER(19) NOT NULL
);


CREATE TABLE TBL_EI_UPDATE_FREQUENCY (
  UPDATE_FREQUENCY_FK NUMBER(19) NOT NULL,
  TBL_OPERATIONS NUMBER(19) NOT NULL
);


CREATE TABLE TBL_FAMILIES_OPERATIONS (
  OPERATION NUMBER(19) NOT NULL,
  FAMILY NUMBER(19) NOT NULL
);


CREATE TABLE TBL_INSTANCES_COSTS (
  COST_FK NUMBER(19) NOT NULL,
  TBL_INSTANCES NUMBER(19) NOT NULL
);



-- Primary keys
    
ALTER TABLE TBL_INTERNATIONAL_STRINGS ADD CONSTRAINT PK_TBL_INTERNATIONAL_STRINGS
	PRIMARY KEY (ID)
;

ALTER TABLE LIS_COLL_METHODS ADD CONSTRAINT PK_LIS_COLL_METHODS
	PRIMARY KEY (ID)
;

ALTER TABLE LIS_COSTS ADD CONSTRAINT PK_LIS_COSTS
	PRIMARY KEY (ID)
;

ALTER TABLE TBL_FAMILIES ADD CONSTRAINT PK_TBL_FAMILIES
	PRIMARY KEY (ID)
;

ALTER TABLE LIS_SURVEY_TYPES ADD CONSTRAINT PK_LIS_SURVEY_TYPES
	PRIMARY KEY (ID)
;

ALTER TABLE LIS_OFFICIALITY_TYPES ADD CONSTRAINT PK_LIS_OFFICIALITY_TYPES
	PRIMARY KEY (ID)
;

ALTER TABLE TBL_OPERATIONS ADD CONSTRAINT PK_TBL_OPERATIONS
	PRIMARY KEY (ID)
;

ALTER TABLE LIS_INSTANCE_TYPES ADD CONSTRAINT PK_LIS_INSTANCE_TYPES
	PRIMARY KEY (ID)
;

ALTER TABLE LIS_SURVEY_SOURCES ADD CONSTRAINT PK_LIS_SURVEY_SOURCES
	PRIMARY KEY (ID)
;

ALTER TABLE TBL_INSTANCES ADD CONSTRAINT PK_TBL_INSTANCES
	PRIMARY KEY (ID)
;

ALTER TABLE TBL_LOCALISED_STRINGS ADD CONSTRAINT PK_TBL_LOCALISED_STRINGS
	PRIMARY KEY (ID)
;

ALTER TABLE TBL_EXTERNAL_ITEMS ADD CONSTRAINT PK_TBL_EXTERNAL_ITEMS
	PRIMARY KEY (ID)
;

    
ALTER TABLE TBL_EI_CLASS_SYSTEM_LISTS ADD CONSTRAINT PK_TBL_EI_CLASS_SYSTEM_LISTS
	PRIMARY KEY (CLASS_SYSTEM_LIST_FK, TBL_INSTANCES)
;

ALTER TABLE TBL_EI_CONC_DEF_LISTS ADD CONSTRAINT PK_TBL_EI_CONC_DEF_LISTS
	PRIMARY KEY (STAT_CONC_DEF_LIST_FK, TBL_INSTANCES)
;

ALTER TABLE TBL_EI_FREQ_COLL ADD CONSTRAINT PK_TBL_EI_FREQ_COLL
	PRIMARY KEY (FREQ_COLL_FK, TBL_INSTANCES)
;

ALTER TABLE TBL_EI_INF_SUPPLIERS ADD CONSTRAINT PK_TBL_EI_INF_SUPPLIERS
	PRIMARY KEY (INFORMATION_SUPPLIERS_FK, TBL_INSTANCES)
;

ALTER TABLE TBL_EI_PRODUCERS ADD CONSTRAINT PK_TBL_EI_PRODUCERS
	PRIMARY KEY (PRODUCER_FK, TBL_OPERATIONS)
;

ALTER TABLE TBL_EI_PUBLISHERS ADD CONSTRAINT PK_TBL_EI_PUBLISHERS
	PRIMARY KEY (PUBLISHER_FK, TBL_OPERATIONS)
;

ALTER TABLE TBL_EI_REG_CONTRIBUTORS ADD CONSTRAINT PK_TBL_EI_REG_CONTRIBUTORS
	PRIMARY KEY (REGIONAL_CONTRIBUTOR_FK, TBL_OPERATIONS)
;

ALTER TABLE TBL_EI_REG_RESPONSIBLES ADD CONSTRAINT PK_TBL_EI_REG_RESPONSIBLES
	PRIMARY KEY (REGIONAL_RESPONSIBLE_FK, TBL_OPERATIONS)
;

ALTER TABLE TBL_EI_SECONDARY_AREAS ADD CONSTRAINT PK_TBL_EI_SECONDARY_AREAS
	PRIMARY KEY (SECUN_SUBJECT_AREAS_FK, TBL_OPERATIONS)
;

ALTER TABLE TBL_EI_STATISTICAL_UNITS ADD CONSTRAINT PK_TBL_EI_STATISTICAL_UNITS
	PRIMARY KEY (STATISTICAL_UNIT_FK, TBL_INSTANCES)
;

ALTER TABLE TBL_EI_UNITS_MEASURE ADD CONSTRAINT PK_TBL_EI_UNITS_MEASURE
	PRIMARY KEY (UNIT_MEASURE_FK, TBL_INSTANCES)
;

ALTER TABLE TBL_EI_UPDATE_FREQUENCY ADD CONSTRAINT PK_TBL_EI_UPDATE_FREQUENCY
	PRIMARY KEY (UPDATE_FREQUENCY_FK, TBL_OPERATIONS)
;

ALTER TABLE TBL_FAMILIES_OPERATIONS ADD CONSTRAINT PK_TBL_FAMILIES_OPERATIONS
	PRIMARY KEY (OPERATION, FAMILY)
;

ALTER TABLE TBL_INSTANCES_COSTS ADD CONSTRAINT PK_TBL_INSTANCES_COSTS
	PRIMARY KEY (COST_FK, TBL_INSTANCES)
;


-- Unique constraints
     
 

ALTER TABLE LIS_COLL_METHODS
    ADD CONSTRAINT UQ_LIS_COLL_METHODS UNIQUE (UUID)
;

 

ALTER TABLE LIS_COSTS
    ADD CONSTRAINT UQ_LIS_COSTS UNIQUE (UUID)
;

 

ALTER TABLE TBL_FAMILIES
    ADD CONSTRAINT UQ_TBL_FAMILIES UNIQUE (UUID)
;

 

ALTER TABLE LIS_SURVEY_TYPES
    ADD CONSTRAINT UQ_LIS_SURVEY_TYPES UNIQUE (UUID)
;

 

ALTER TABLE LIS_OFFICIALITY_TYPES
    ADD CONSTRAINT UQ_LIS_OFFICIALITY_TYPES UNIQUE (UUID)
;

 

ALTER TABLE TBL_OPERATIONS
    ADD CONSTRAINT UQ_TBL_OPERATIONS UNIQUE (UUID)
;

 

ALTER TABLE LIS_INSTANCE_TYPES
    ADD CONSTRAINT UQ_LIS_INSTANCE_TYPES UNIQUE (UUID)
;

 

ALTER TABLE LIS_SURVEY_SOURCES
    ADD CONSTRAINT UQ_LIS_SURVEY_SOURCES UNIQUE (UUID)
;

 

ALTER TABLE TBL_INSTANCES
    ADD CONSTRAINT UQ_TBL_INSTANCES UNIQUE (UUID)
;

 
 

ALTER TABLE TBL_EXTERNAL_ITEMS
    ADD CONSTRAINT UQ_TBL_EXTERNAL_ITEMS UNIQUE (UUID)
;



-- Foreign key constraints
    

  
ALTER TABLE TBL_LOCALISED_STRINGS ADD CONSTRAINT FK_TBL_LOCALISED_STRINGS_TBL13
	FOREIGN KEY (INTERNATIONAL_STRING_FK) REFERENCES TBL_INTERNATIONAL_STRINGS (ID)
;

ALTER TABLE LIS_COLL_METHODS ADD CONSTRAINT FK_LIS_COLL_METHODS_DESCRIPT27
	FOREIGN KEY (DESCRIPTION) REFERENCES TBL_INTERNATIONAL_STRINGS (ID)
;

  
ALTER TABLE LIS_COSTS ADD CONSTRAINT FK_LIS_COSTS_DESCRIPTION
	FOREIGN KEY (DESCRIPTION) REFERENCES TBL_INTERNATIONAL_STRINGS (ID)
;

  
ALTER TABLE TBL_FAMILIES ADD CONSTRAINT FK_TBL_FAMILIES_TITLE_FK
	FOREIGN KEY (TITLE_FK) REFERENCES TBL_INTERNATIONAL_STRINGS (ID)
;
ALTER TABLE TBL_FAMILIES ADD CONSTRAINT FK_TBL_FAMILIES_ACRONYM_FK
	FOREIGN KEY (ACRONYM_FK) REFERENCES TBL_INTERNATIONAL_STRINGS (ID)
;
ALTER TABLE TBL_FAMILIES ADD CONSTRAINT FK_TBL_FAMILIES_DESCRIPTION_FK
	FOREIGN KEY (DESCRIPTION_FK) REFERENCES TBL_INTERNATIONAL_STRINGS (ID)
;

  
ALTER TABLE LIS_SURVEY_TYPES ADD CONSTRAINT FK_LIS_SURVEY_TYPES_DESCRIPT66
	FOREIGN KEY (DESCRIPTION) REFERENCES TBL_INTERNATIONAL_STRINGS (ID)
;

  
ALTER TABLE LIS_OFFICIALITY_TYPES ADD CONSTRAINT FK_LIS_OFFICIALITY_TYPES_DES93
	FOREIGN KEY (DESCRIPTION) REFERENCES TBL_INTERNATIONAL_STRINGS (ID)
;

  
ALTER TABLE TBL_OPERATIONS ADD CONSTRAINT FK_TBL_OPERATIONS_TITLE_FK
	FOREIGN KEY (TITLE_FK) REFERENCES TBL_INTERNATIONAL_STRINGS (ID)
;
ALTER TABLE TBL_OPERATIONS ADD CONSTRAINT FK_TBL_OPERATIONS_ACRONYM_FK
	FOREIGN KEY (ACRONYM_FK) REFERENCES TBL_INTERNATIONAL_STRINGS (ID)
;
ALTER TABLE TBL_OPERATIONS ADD CONSTRAINT FK_TBL_OPERATIONS_OBJECTIVE_FK
	FOREIGN KEY (OBJECTIVE_FK) REFERENCES TBL_INTERNATIONAL_STRINGS (ID)
;
ALTER TABLE TBL_OPERATIONS ADD CONSTRAINT FK_TBL_OPERATIONS_DESCRIPTIO78
	FOREIGN KEY (DESCRIPTION_FK) REFERENCES TBL_INTERNATIONAL_STRINGS (ID)
;
ALTER TABLE TBL_OPERATIONS ADD CONSTRAINT FK_TBL_OPERATIONS_SURVEY_TYP07
	FOREIGN KEY (SURVEY_TYPE_FK) REFERENCES LIS_SURVEY_TYPES (ID)
;
ALTER TABLE TBL_OPERATIONS ADD CONSTRAINT FK_TBL_OPERATIONS_OFFICIALIT80
	FOREIGN KEY (OFFICIALITY_TYPE_FK) REFERENCES LIS_OFFICIALITY_TYPES (ID)
;
ALTER TABLE TBL_OPERATIONS ADD CONSTRAINT FK_TBL_OPERATIONS_REL_POL_US21
	FOREIGN KEY (REL_POL_US_AC_FK) REFERENCES TBL_INTERNATIONAL_STRINGS (ID)
;
ALTER TABLE TBL_OPERATIONS ADD CONSTRAINT FK_TBL_OPERATIONS_REV_POLICY04
	FOREIGN KEY (REV_POLICY_FK) REFERENCES TBL_INTERNATIONAL_STRINGS (ID)
;
ALTER TABLE TBL_OPERATIONS ADD CONSTRAINT FK_TBL_OPERATIONS_REV_PRACTI41
	FOREIGN KEY (REV_PRACTICE_FK) REFERENCES TBL_INTERNATIONAL_STRINGS (ID)
;
ALTER TABLE TBL_OPERATIONS ADD CONSTRAINT FK_TBL_OPERATIONS_COMMENT_FK
	FOREIGN KEY (COMMENT_FK) REFERENCES TBL_INTERNATIONAL_STRINGS (ID)
;
ALTER TABLE TBL_OPERATIONS ADD CONSTRAINT FK_TBL_OPERATIONS_NOTES_FK
	FOREIGN KEY (NOTES_FK) REFERENCES TBL_INTERNATIONAL_STRINGS (ID)
;

  
ALTER TABLE LIS_INSTANCE_TYPES ADD CONSTRAINT FK_LIS_INSTANCE_TYPES_DESCRI61
	FOREIGN KEY (DESCRIPTION) REFERENCES TBL_INTERNATIONAL_STRINGS (ID)
;

  
ALTER TABLE LIS_SURVEY_SOURCES ADD CONSTRAINT FK_LIS_SURVEY_SOURCES_DESCRI69
	FOREIGN KEY (DESCRIPTION) REFERENCES TBL_INTERNATIONAL_STRINGS (ID)
;

  
ALTER TABLE TBL_INSTANCES ADD CONSTRAINT FK_TBL_INSTANCES_TITLE_FK
	FOREIGN KEY (TITLE_FK) REFERENCES TBL_INTERNATIONAL_STRINGS (ID)
;
ALTER TABLE TBL_INSTANCES ADD CONSTRAINT FK_TBL_INSTANCES_ACRONYM_FK
	FOREIGN KEY (ACRONYM_FK) REFERENCES TBL_INTERNATIONAL_STRINGS (ID)
;
ALTER TABLE TBL_INSTANCES ADD CONSTRAINT FK_TBL_INSTANCES_OPERATION_FK
	FOREIGN KEY (OPERATION_FK) REFERENCES TBL_OPERATIONS (ID) ON DELETE CASCADE
;
ALTER TABLE TBL_INSTANCES ADD CONSTRAINT FK_TBL_INSTANCES_DATA_DESCRI51
	FOREIGN KEY (DATA_DESCRIPTION_FK) REFERENCES TBL_INTERNATIONAL_STRINGS (ID)
;
ALTER TABLE TBL_INSTANCES ADD CONSTRAINT FK_TBL_INSTANCES_STATISTICAL57
	FOREIGN KEY (STATISTICAL_POPULATION_FK) REFERENCES TBL_INTERNATIONAL_STRINGS (ID)
;
ALTER TABLE TBL_INSTANCES ADD CONSTRAINT FK_TBL_INSTANCES_GEOGRAPHIC_84
	FOREIGN KEY (GEOGRAPHIC_COMPARABILITY_FK) REFERENCES TBL_INTERNATIONAL_STRINGS (ID)
;
ALTER TABLE TBL_INSTANCES ADD CONSTRAINT FK_TBL_INSTANCES_TEMPORAL_CO57
	FOREIGN KEY (TEMPORAL_COMPARABILITY_FK) REFERENCES TBL_INTERNATIONAL_STRINGS (ID)
;
ALTER TABLE TBL_INSTANCES ADD CONSTRAINT FK_TBL_INSTANCES_STAT_CONC_D36
	FOREIGN KEY (STAT_CONC_DEF_FK) REFERENCES TBL_INTERNATIONAL_STRINGS (ID)
;
ALTER TABLE TBL_INSTANCES ADD CONSTRAINT FK_TBL_INSTANCES_CLASS_SYSTE36
	FOREIGN KEY (CLASS_SYSTEM_FK) REFERENCES TBL_INTERNATIONAL_STRINGS (ID)
;
ALTER TABLE TBL_INSTANCES ADD CONSTRAINT FK_TBL_INSTANCES_INSTANCE_TY30
	FOREIGN KEY (INSTANCE_TYPE_FK) REFERENCES LIS_INSTANCE_TYPES (ID)
;
ALTER TABLE TBL_INSTANCES ADD CONSTRAINT FK_TBL_INSTANCES_DOC_METHOD_FK
	FOREIGN KEY (DOC_METHOD_FK) REFERENCES TBL_INTERNATIONAL_STRINGS (ID)
;
ALTER TABLE TBL_INSTANCES ADD CONSTRAINT FK_TBL_INSTANCES_SURVEY_SOUR62
	FOREIGN KEY (SURVEY_SOURCE_FK) REFERENCES LIS_SURVEY_SOURCES (ID)
;
ALTER TABLE TBL_INSTANCES ADD CONSTRAINT FK_TBL_INSTANCES_COLL_METHOD70
	FOREIGN KEY (COLL_METHOD_FK) REFERENCES LIS_COLL_METHODS (ID)
;
ALTER TABLE TBL_INSTANCES ADD CONSTRAINT FK_TBL_INSTANCES_DATA_VALIDA20
	FOREIGN KEY (DATA_VALIDATION_FK) REFERENCES TBL_INTERNATIONAL_STRINGS (ID)
;
ALTER TABLE TBL_INSTANCES ADD CONSTRAINT FK_TBL_INSTANCES_DATA_COMPIL04
	FOREIGN KEY (DATA_COMPILATION_FK) REFERENCES TBL_INTERNATIONAL_STRINGS (ID)
;
ALTER TABLE TBL_INSTANCES ADD CONSTRAINT FK_TBL_INSTANCES_ADJUSTMENT_FK
	FOREIGN KEY (ADJUSTMENT_FK) REFERENCES TBL_INTERNATIONAL_STRINGS (ID)
;
ALTER TABLE TBL_INSTANCES ADD CONSTRAINT FK_TBL_INSTANCES_COST_BURDEN50
	FOREIGN KEY (COST_BURDEN_FK) REFERENCES TBL_INTERNATIONAL_STRINGS (ID)
;
ALTER TABLE TBL_INSTANCES ADD CONSTRAINT FK_TBL_INSTANCES_QUALITY_DOC58
	FOREIGN KEY (QUALITY_DOC_FK) REFERENCES TBL_INTERNATIONAL_STRINGS (ID)
;
ALTER TABLE TBL_INSTANCES ADD CONSTRAINT FK_TBL_INSTANCES_QUALITY_ASS85
	FOREIGN KEY (QUALITY_ASSURE_FK) REFERENCES TBL_INTERNATIONAL_STRINGS (ID)
;
ALTER TABLE TBL_INSTANCES ADD CONSTRAINT FK_TBL_INSTANCES_QUALITY_ASS12
	FOREIGN KEY (QUALITY_ASSMNT_FK) REFERENCES TBL_INTERNATIONAL_STRINGS (ID)
;
ALTER TABLE TBL_INSTANCES ADD CONSTRAINT FK_TBL_INSTANCES_USER_NEEDS_FK
	FOREIGN KEY (USER_NEEDS_FK) REFERENCES TBL_INTERNATIONAL_STRINGS (ID)
;
ALTER TABLE TBL_INSTANCES ADD CONSTRAINT FK_TBL_INSTANCES_USER_SAT_FK
	FOREIGN KEY (USER_SAT_FK) REFERENCES TBL_INTERNATIONAL_STRINGS (ID)
;
ALTER TABLE TBL_INSTANCES ADD CONSTRAINT FK_TBL_INSTANCES_COMPLETENES70
	FOREIGN KEY (COMPLETENESS_FK) REFERENCES TBL_INTERNATIONAL_STRINGS (ID)
;
ALTER TABLE TBL_INSTANCES ADD CONSTRAINT FK_TBL_INSTANCES_TIMELINESS_FK
	FOREIGN KEY (TIMELINESS_FK) REFERENCES TBL_INTERNATIONAL_STRINGS (ID)
;
ALTER TABLE TBL_INSTANCES ADD CONSTRAINT FK_TBL_INSTANCES_PUNCTUALITY14
	FOREIGN KEY (PUNCTUALITY_FK) REFERENCES TBL_INTERNATIONAL_STRINGS (ID)
;
ALTER TABLE TBL_INSTANCES ADD CONSTRAINT FK_TBL_INSTANCES_ACCURACY_OV67
	FOREIGN KEY (ACCURACY_OVERALL_FK) REFERENCES TBL_INTERNATIONAL_STRINGS (ID)
;
ALTER TABLE TBL_INSTANCES ADD CONSTRAINT FK_TBL_INSTANCES_SAMPLING_ER13
	FOREIGN KEY (SAMPLING_ERR_FK) REFERENCES TBL_INTERNATIONAL_STRINGS (ID)
;
ALTER TABLE TBL_INSTANCES ADD CONSTRAINT FK_TBL_INSTANCES_NONSAMPLING20
	FOREIGN KEY (NONSAMPLING_ERR_FK) REFERENCES TBL_INTERNATIONAL_STRINGS (ID)
;
ALTER TABLE TBL_INSTANCES ADD CONSTRAINT FK_TBL_INSTANCES_COHER_X_DOM37
	FOREIGN KEY (COHER_X_DOMAIN_FK) REFERENCES TBL_INTERNATIONAL_STRINGS (ID)
;
ALTER TABLE TBL_INSTANCES ADD CONSTRAINT FK_TBL_INSTANCES_COHER_INTER55
	FOREIGN KEY (COHER_INTERNAL_FK) REFERENCES TBL_INTERNATIONAL_STRINGS (ID)
;
ALTER TABLE TBL_INSTANCES ADD CONSTRAINT FK_TBL_INSTANCES_COMMENT_FK
	FOREIGN KEY (COMMENT_FK) REFERENCES TBL_INTERNATIONAL_STRINGS (ID)
;
ALTER TABLE TBL_INSTANCES ADD CONSTRAINT FK_TBL_INSTANCES_NOTES_FK
	FOREIGN KEY (NOTES_FK) REFERENCES TBL_INTERNATIONAL_STRINGS (ID)
;

  
  
  
  
  

ALTER TABLE TBL_EI_CLASS_SYSTEM_LISTS ADD CONSTRAINT FK_TBL_EI_CLASS_SYSTEM_LISTS18
	FOREIGN KEY (CLASS_SYSTEM_LIST_FK) REFERENCES TBL_EXTERNAL_ITEMS (ID)
;
ALTER TABLE TBL_EI_CLASS_SYSTEM_LISTS ADD CONSTRAINT FK_TBL_EI_CLASS_SYSTEM_LISTS04
	FOREIGN KEY (TBL_INSTANCES) REFERENCES TBL_INSTANCES (ID)
;

  
ALTER TABLE TBL_EI_CONC_DEF_LISTS ADD CONSTRAINT FK_TBL_EI_CONC_DEF_LISTS_STA57
	FOREIGN KEY (STAT_CONC_DEF_LIST_FK) REFERENCES TBL_EXTERNAL_ITEMS (ID)
;
ALTER TABLE TBL_EI_CONC_DEF_LISTS ADD CONSTRAINT FK_TBL_EI_CONC_DEF_LISTS_TBL61
	FOREIGN KEY (TBL_INSTANCES) REFERENCES TBL_INSTANCES (ID)
;

  
ALTER TABLE TBL_EI_FREQ_COLL ADD CONSTRAINT FK_TBL_EI_FREQ_COLL_FREQ_COL43
	FOREIGN KEY (FREQ_COLL_FK) REFERENCES TBL_EXTERNAL_ITEMS (ID)
;
ALTER TABLE TBL_EI_FREQ_COLL ADD CONSTRAINT FK_TBL_EI_FREQ_COLL_TBL_INST35
	FOREIGN KEY (TBL_INSTANCES) REFERENCES TBL_INSTANCES (ID)
;

  
ALTER TABLE TBL_EI_INF_SUPPLIERS ADD CONSTRAINT FK_TBL_EI_INF_SUPPLIERS_INFO60
	FOREIGN KEY (INFORMATION_SUPPLIERS_FK) REFERENCES TBL_EXTERNAL_ITEMS (ID)
;
ALTER TABLE TBL_EI_INF_SUPPLIERS ADD CONSTRAINT FK_TBL_EI_INF_SUPPLIERS_TBL_57
	FOREIGN KEY (TBL_INSTANCES) REFERENCES TBL_INSTANCES (ID)
;

  
ALTER TABLE TBL_EI_PRODUCERS ADD CONSTRAINT FK_TBL_EI_PRODUCERS_PRODUCER86
	FOREIGN KEY (PRODUCER_FK) REFERENCES TBL_EXTERNAL_ITEMS (ID)
;
ALTER TABLE TBL_EI_PRODUCERS ADD CONSTRAINT FK_TBL_EI_PRODUCERS_TBL_OPER21
	FOREIGN KEY (TBL_OPERATIONS) REFERENCES TBL_OPERATIONS (ID)
;

  
ALTER TABLE TBL_EI_PUBLISHERS ADD CONSTRAINT FK_TBL_EI_PUBLISHERS_PUBLISH06
	FOREIGN KEY (PUBLISHER_FK) REFERENCES TBL_EXTERNAL_ITEMS (ID)
;
ALTER TABLE TBL_EI_PUBLISHERS ADD CONSTRAINT FK_TBL_EI_PUBLISHERS_TBL_OPE97
	FOREIGN KEY (TBL_OPERATIONS) REFERENCES TBL_OPERATIONS (ID)
;

  
ALTER TABLE TBL_EI_REG_CONTRIBUTORS ADD CONSTRAINT FK_TBL_EI_REG_CONTRIBUTORS_R55
	FOREIGN KEY (REGIONAL_CONTRIBUTOR_FK) REFERENCES TBL_EXTERNAL_ITEMS (ID)
;
ALTER TABLE TBL_EI_REG_CONTRIBUTORS ADD CONSTRAINT FK_TBL_EI_REG_CONTRIBUTORS_T61
	FOREIGN KEY (TBL_OPERATIONS) REFERENCES TBL_OPERATIONS (ID)
;

  
ALTER TABLE TBL_EI_REG_RESPONSIBLES ADD CONSTRAINT FK_TBL_EI_REG_RESPONSIBLES_R91
	FOREIGN KEY (REGIONAL_RESPONSIBLE_FK) REFERENCES TBL_EXTERNAL_ITEMS (ID)
;
ALTER TABLE TBL_EI_REG_RESPONSIBLES ADD CONSTRAINT FK_TBL_EI_REG_RESPONSIBLES_T70
	FOREIGN KEY (TBL_OPERATIONS) REFERENCES TBL_OPERATIONS (ID)
;

  
ALTER TABLE TBL_EI_SECONDARY_AREAS ADD CONSTRAINT FK_TBL_EI_SECONDARY_AREAS_SE96
	FOREIGN KEY (SECUN_SUBJECT_AREAS_FK) REFERENCES TBL_EXTERNAL_ITEMS (ID)
;
ALTER TABLE TBL_EI_SECONDARY_AREAS ADD CONSTRAINT FK_TBL_EI_SECONDARY_AREAS_TB37
	FOREIGN KEY (TBL_OPERATIONS) REFERENCES TBL_OPERATIONS (ID)
;

  
ALTER TABLE TBL_EI_STATISTICAL_UNITS ADD CONSTRAINT FK_TBL_EI_STATISTICAL_UNITS_98
	FOREIGN KEY (STATISTICAL_UNIT_FK) REFERENCES TBL_EXTERNAL_ITEMS (ID)
;
ALTER TABLE TBL_EI_STATISTICAL_UNITS ADD CONSTRAINT FK_TBL_EI_STATISTICAL_UNITS_55
	FOREIGN KEY (TBL_INSTANCES) REFERENCES TBL_INSTANCES (ID)
;

  
ALTER TABLE TBL_EI_UNITS_MEASURE ADD CONSTRAINT FK_TBL_EI_UNITS_MEASURE_UNIT46
	FOREIGN KEY (UNIT_MEASURE_FK) REFERENCES TBL_EXTERNAL_ITEMS (ID)
;
ALTER TABLE TBL_EI_UNITS_MEASURE ADD CONSTRAINT FK_TBL_EI_UNITS_MEASURE_TBL_70
	FOREIGN KEY (TBL_INSTANCES) REFERENCES TBL_INSTANCES (ID)
;

  
ALTER TABLE TBL_EI_UPDATE_FREQUENCY ADD CONSTRAINT FK_TBL_EI_UPDATE_FREQUENCY_U63
	FOREIGN KEY (UPDATE_FREQUENCY_FK) REFERENCES TBL_EXTERNAL_ITEMS (ID)
;
ALTER TABLE TBL_EI_UPDATE_FREQUENCY ADD CONSTRAINT FK_TBL_EI_UPDATE_FREQUENCY_T76
	FOREIGN KEY (TBL_OPERATIONS) REFERENCES TBL_OPERATIONS (ID)
;

  
ALTER TABLE TBL_FAMILIES_OPERATIONS ADD CONSTRAINT FK_TBL_FAMILIES_OPERATIONS_O04
	FOREIGN KEY (OPERATION) REFERENCES TBL_OPERATIONS (ID)
;
ALTER TABLE TBL_FAMILIES_OPERATIONS ADD CONSTRAINT FK_TBL_FAMILIES_OPERATIONS_F79
	FOREIGN KEY (FAMILY) REFERENCES TBL_FAMILIES (ID)
;

  
ALTER TABLE TBL_INSTANCES_COSTS ADD CONSTRAINT FK_TBL_INSTANCES_COSTS_COST_FK
	FOREIGN KEY (COST_FK) REFERENCES LIS_COSTS (ID)
;
ALTER TABLE TBL_INSTANCES_COSTS ADD CONSTRAINT FK_TBL_INSTANCES_COSTS_TBL_I78
	FOREIGN KEY (TBL_INSTANCES) REFERENCES TBL_INSTANCES (ID)
;

  


-- Index
  
  
  
  
  
  


