ALTER TABLE TB_FAMILIES MODIFY  (
    PROC_STATUS VARCHAR2(255)
);


ALTER TABLE TB_EXTERNAL_ITEMS MODIFY  (
    MANAGEMENT_APP_URL VARCHAR2(4000),
    TYPE VARCHAR2(255)
);

ALTER TABLE TB_OPERATIONS MODIFY  (
    PROC_STATUS VARCHAR2(255),
    STATUS VARCHAR2(255)
);

ALTER TABLE TB_INSTANCES MODIFY  (
    PROC_STATUS VARCHAR2(255)
);
