{
   "swagger":"2.0",
   "info":{
      "description":"Las operaciones estadísticas son el elemento principal sobre el que se define toda la actividad estadística del organismo. Todos los recursos que se publican en el organismo guardan relación de manera directa o indirecta con la operación estadística. La API de operaciones estadísticas permite consultar el inventario de operaciones estadísticas del organismo, las diferencias que existen entre las diferentes realizaciones de una misma operación estadística (instancias) y su agrupación en familias.",
      "version":"1.0",
      "title":"API de operaciones estadísticas v1.0"
   },
   "host":"<%=org.siemac.metamac.statistical.operations.web.external.WebUtils.getApiBaseURL()%>",
   "schemes":[

   ],
   "tags":[
      {
         "name":"Familias de operaciones",
         "description":""
      },
      {
         "name":"Operaciones estadísticas",
         "description":""
      },
      {
         "name":"Tablas de valores auxiliares",
         "description":""
      }
   ],
   "definitions":{
      "ClassSystems":{
         "type":"object",
         "title":"ClassSystems",
         "allOf":[
            {
               "$ref":"#/definitions/ListBase"
            },
            {
               "properties":{
                  "classSystem":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"",
                     "$ref":"#/definitions/Resource"
                  }
               }
            }
         ],
         "description":"Clasificaciones usadas en la instancia de la operación estadística."
      },
      "CollMethods":{
         "type":"object",
         "title":"CollMethods",
         "allOf":[
            {
               "$ref":"#/definitions/ListBase"
            },
            {
               "properties":{
                  "collMethod":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"",
                     "$ref":"#/definitions/Item"
                  }
               }
            }
         ],
         "description":"Valores aceptados para los métodos de recolección de los datos"
      },
      "Costs":{
         "type":"object",
         "title":"Costs",
         "allOf":[
            {
               "$ref":"#/definitions/ListBase"
            },
            {
               "properties":{
                  "cost":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"",
                     "$ref":"#/definitions/Item"
                  }
               }
            }
         ],
         "description":"Valores aceptados para los tipos de costes asociados a la operación."
      },
      "DataSharings":{
         "type":"object",
         "title":"DataSharings",
         "allOf":[
            {
               "$ref":"#/definitions/ListBase"
            },
            {
               "properties":{
                  "dataSharing":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"",
                     "$ref":"#/definitions/InternationalString"
                  }
               }
            }
         ],
         "description":"Acuerdos y convenios existentes entre organizaciones productoras de datos para la coordinación y compartición de los mismos. "
      },
      "Families":{
         "type":"object",
         "title":"Families",
         "allOf":[
            {
               "$ref":"#/definitions/ListBase"
            },
            {
               "properties":{
                  "family":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"",
                     "$ref":"#/definitions/Resource"
                  }
               }
            }
         ],
         "description":"Listado de familias en las que se agrupan las diferentes operaciones estadísticas"
      },
      "Family":{
         "type":"object",
         "title":"Family",
         "allOf":[
            {
               "properties":{
                  "kind":{
                     "xml":{
                        "attribute":true,
                        "namespace":""
                     },
                     "description":"",
                     "type":"string"
                  },
                  "acronym":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"",
                     "$ref":"#/definitions/InternationalString"
                  },
                  "childLinks":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"",
                     "$ref":"#/definitions/ChildLinks"
                  },
                  "description":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"",
                     "$ref":"#/definitions/InternationalString"
                  },
                  "id":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"",
                     "type":"string"
                  },
                  "inventoryDate":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"",
                     "type":"string"
                  },
                  "name":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"",
                     "$ref":"#/definitions/InternationalString"
                  },
                  "parentLink":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"",
                     "$ref":"#/definitions/ResourceLink"
                  },
                  "selfLink":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"",
                     "$ref":"#/definitions/ResourceLink"
                  },
                  "urn":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"",
                     "type":"string"
                  }
               }
            }
         ],
         "description":"Familia de operaciones estadísticas"
      },
      "FreqColls":{
         "type":"object",
         "title":"FreqColls",
         "allOf":[
            {
               "$ref":"#/definitions/ListBase"
            },
            {
               "properties":{
                  "freqColl":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"",
                     "$ref":"#/definitions/Resource"
                  }
               }
            }
         ],
         "description":"Frecuencias de recolección de los datos."
      },
      "GeographicGranularities":{
         "type":"object",
         "title":"GeographicGranularities",
         "allOf":[
            {
               "$ref":"#/definitions/ListBase"
            },
            {
               "properties":{
                  "geographicGranularity":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"",
                     "$ref":"#/definitions/Resource"
                  }
               }
            }
         ],
         "description":"Granularidades geográficas."
      },
      "InformationSuppliers":{
         "type":"object",
         "title":"InformationSuppliers",
         "allOf":[
            {
               "$ref":"#/definitions/ListBase"
            },
            {
               "properties":{
                  "informationSupplier":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"",
                     "$ref":"#/definitions/Resource"
                  }
               }
            }
         ],
         "description":"Organizaciones obligadas a suministrar información para la elaboración de la operación estadística."
      },
      "Instance":{
         "type":"object",
         "title":"Instance",
         "allOf":[
            {
               "properties":{
                  "kind":{
                     "xml":{
                        "attribute":true,
                        "namespace":""
                     },
                     "description":"",
                     "type":"string"
                  },
                  "accuracyOverall":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"",
                     "$ref":"#/definitions/InternationalString"
                  },
                  "acronym":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"",
                     "$ref":"#/definitions/InternationalString"
                  },
                  "adjustment":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"",
                     "$ref":"#/definitions/InternationalString"
                  },
                  "basePeriod":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"",
                     "type":"string"
                  },
                  "childLinks":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"",
                     "$ref":"#/definitions/ChildLinks"
                  },
                  "classSystems":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"",
                     "$ref":"#/definitions/ClassSystems"
                  },
                  "classSystemsDescription":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"",
                     "$ref":"#/definitions/InternationalString"
                  },
                  "coherInternal":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"",
                     "$ref":"#/definitions/InternationalString"
                  },
                  "coherXDom":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"",
                     "$ref":"#/definitions/InternationalString"
                  },
                  "collMethod":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"",
                     "$ref":"#/definitions/Item"
                  },
                  "comment":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"",
                     "$ref":"#/definitions/InternationalString"
                  },
                  "completeness":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"",
                     "$ref":"#/definitions/InternationalString"
                  },
                  "dataCompilation":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"",
                     "$ref":"#/definitions/InternationalString"
                  },
                  "dataDescription":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"",
                     "$ref":"#/definitions/InternationalString"
                  },
                  "dataValidation":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"",
                     "$ref":"#/definitions/InternationalString"
                  },
                  "docMethod":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"",
                     "$ref":"#/definitions/InternationalString"
                  },
                  "freqColls":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"",
                     "$ref":"#/definitions/FreqColls"
                  },
                  "geographicComparability":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"",
                     "$ref":"#/definitions/InternationalString"
                  },
                  "geographicGranularity":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"",
                     "$ref":"#/definitions/GeographicGranularities"
                  },
                  "id":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"",
                     "type":"string"
                  },
                  "informationSuppliers":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"",
                     "$ref":"#/definitions/InformationSuppliers"
                  },
                  "inventoryDate":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"",
                     "type":"string"
                  },
                  "measures":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"",
                     "$ref":"#/definitions/Measures"
                  },
                  "name":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"",
                     "$ref":"#/definitions/InternationalString"
                  },
                  "nonsamplingErr":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"",
                     "$ref":"#/definitions/InternationalString"
                  },
                  "parentLink":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"",
                     "$ref":"#/definitions/ResourceLink"
                  },
                  "predecessor":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"",
                     "$ref":"#/definitions/Resource"
                  },
                  "punctuality":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"",
                     "$ref":"#/definitions/InternationalString"
                  },
                  "qualityAssmnt":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"",
                     "$ref":"#/definitions/InternationalString"
                  },
                  "qualityAssure":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"",
                     "$ref":"#/definitions/InternationalString"
                  },
                  "qualityDoc":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"",
                     "$ref":"#/definitions/InternationalString"
                  },
                  "samplingErr":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"",
                     "$ref":"#/definitions/InternationalString"
                  },
                  "selfLink":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"",
                     "$ref":"#/definitions/ResourceLink"
                  },
                  "statConcDefs":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"",
                     "$ref":"#/definitions/StatConcDefs"
                  },
                  "statConcDefsDescription":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"",
                     "$ref":"#/definitions/InternationalString"
                  },
                  "statisticalOperation":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"",
                     "$ref":"#/definitions/Resource"
                  },
                  "statisticalOperationSource":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"",
                     "$ref":"#/definitions/Item"
                  },
                  "statisticalPopulation":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"",
                     "$ref":"#/definitions/InternationalString"
                  },
                  "statisticalUnits":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"",
                     "$ref":"#/definitions/StatisticalUnits"
                  },
                  "successor":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"",
                     "$ref":"#/definitions/Resource"
                  },
                  "temporalComparability":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"",
                     "$ref":"#/definitions/InternationalString"
                  },
                  "temporalGranularity":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"",
                     "$ref":"#/definitions/TemporalGranularities"
                  },
                  "timeliness":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"",
                     "$ref":"#/definitions/InternationalString"
                  },
                  "urn":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"",
                     "type":"string"
                  },
                  "userNeeds":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"",
                     "$ref":"#/definitions/InternationalString"
                  },
                  "userSat":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"",
                     "$ref":"#/definitions/InternationalString"
                  }
               }
            }
         ],
         "description":"La instancia de operación estadística es cada una de las realizaciones de una misma operación estadística. Las instancias pueden ser de dos tipos: SERIE o SECCIÓN. Las instancias de tipo serie proveen información de una serie temporal completa y la instancia acaba cuando se produce una rotura de la serie. Las instancias de tipo sección proveen información de un único instante de tiempo."
      },
      "InstanceTypes":{
         "type":"object",
         "title":"InstanceTypes",
         "allOf":[
            {
               "$ref":"#/definitions/ListBase"
            },
            {
               "properties":{
                  "instanceType":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"",
                     "$ref":"#/definitions/Item"
                  }
               }
            }
         ],
         "description":"Tipos de instancias"
      },
      "Instances":{
         "type":"object",
         "title":"Instances",
         "allOf":[
            {
               "$ref":"#/definitions/ListBase"
            },
            {
               "properties":{
                  "instance":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"",
                     "$ref":"#/definitions/Resource"
                  }
               }
            }
         ],
         "description":"Listados de instancias de operaciones estadísticas."
      },
      "LegalActs":{
         "type":"object",
         "title":"LegalActs",
         "allOf":[
            {
               "$ref":"#/definitions/ListBase"
            },
            {
               "properties":{
                  "legalActs":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"",
                     "$ref":"#/definitions/InternationalString"
                  }
               }
            }
         ],
         "description":"Leyes u otro tipo de convenios (formales o informales) que otorgan reponsabilidad y autoridad al organismo para la recolección, procesado y diseminación de la estadística."
      },
      "Measures":{
         "type":"object",
         "title":"Measures",
         "allOf":[
            {
               "$ref":"#/definitions/ListBase"
            },
            {
               "properties":{
                  "measure":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"",
                     "$ref":"#/definitions/Resource"
                  }
               }
            }
         ],
         "description":"Unidades en las que se miden los datos."
      },
      "OfficialityTypes":{
         "type":"object",
         "title":"OfficialityTypes",
         "allOf":[
            {
               "$ref":"#/definitions/ListBase"
            },
            {
               "properties":{
                  "officialityType":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"",
                     "$ref":"#/definitions/Item"
                  }
               }
            }
         ],
         "description":"Tipos de oficialidad que se le puede asignar a una operación estadística."
      },
      "Operation":{
         "type":"object",
         "title":"Operation",
         "allOf":[
            {
               "properties":{
                  "kind":{
                     "xml":{
                        "attribute":true,
                        "namespace":""
                     },
                     "description":"",
                     "type":"string"
                  },
                  "acronym":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"",
                     "$ref":"#/definitions/InternationalString"
                  },
                  "childLinks":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"",
                     "$ref":"#/definitions/ChildLinks"
                  },
                  "comment":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"",
                     "$ref":"#/definitions/InternationalString"
                  },
                  "confidentialityDataTreatment":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"",
                     "$ref":"#/definitions/InternationalString"
                  },
                  "confidentialityPolicy":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"",
                     "$ref":"#/definitions/InternationalString"
                  },
                  "contact":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"",
                     "$ref":"#/definitions/Resource"
                  },
                  "currentInstance":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"",
                     "$ref":"#/definitions/Resource"
                  },
                  "currentlyActive":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"",
                     "type":"boolean"
                  },
                  "dataSharings":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"",
                     "$ref":"#/definitions/DataSharings"
                  },
                  "description":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"",
                     "$ref":"#/definitions/InternationalString"
                  },
                  "id":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"",
                     "type":"string"
                  },
                  "indicatorSystem":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"",
                     "type":"boolean"
                  },
                  "inventoryDate":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"",
                     "type":"string"
                  },
                  "legalActs":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"",
                     "$ref":"#/definitions/LegalActs"
                  },
                  "name":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"",
                     "$ref":"#/definitions/InternationalString"
                  },
                  "objective":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"",
                     "$ref":"#/definitions/InternationalString"
                  },
                  "officialityType":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"",
                     "$ref":"#/definitions/Item"
                  },
                  "parentLink":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"",
                     "$ref":"#/definitions/ResourceLink"
                  },
                  "producers":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"",
                     "$ref":"#/definitions/Producers"
                  },
                  "publishers":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"",
                     "$ref":"#/definitions/Publishers"
                  },
                  "regionalContributors":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"",
                     "$ref":"#/definitions/RegionalContributors"
                  },
                  "regionalResponsibles":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"",
                     "$ref":"#/definitions/RegionalResponsibles"
                  },
                  "relPolUsAc":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"",
                     "$ref":"#/definitions/InternationalString"
                  },
                  "releaseCalendar":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"",
                     "type":"boolean"
                  },
                  "releaseCalendarAccess":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"",
                     "type":"string"
                  },
                  "revPolicy":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"",
                     "$ref":"#/definitions/InternationalString"
                  },
                  "revPractice":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"",
                     "$ref":"#/definitions/InternationalString"
                  },
                  "secondarySubjectAreas":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"",
                     "$ref":"#/definitions/SecondarySubjectAreas"
                  },
                  "selfLink":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"",
                     "$ref":"#/definitions/ResourceLink"
                  },
                  "statisticalOperationType":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"",
                     "$ref":"#/definitions/Item"
                  },
                  "status":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"",
                     "$ref":"#/definitions/Status"
                  },
                  "subjectArea":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"",
                     "$ref":"#/definitions/Resource"
                  },
                  "updateFrequencies":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"",
                     "$ref":"#/definitions/UpdateFrequencies"
                  },
                  "urn":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"",
                     "type":"string"
                  }
               }
            }
         ],
         "description":"Conjunto de actividades, incluidas las preparatorias, que conducen a la obtención y/o difusión de resultados estadísticos sobre un determinado sector o tema o territorio. También se incluyen en el ámbito de esta definición los trabajos de infraestructura y de normalización estadística que posibilitan la coordinación, homogeneización e integración de las estadísticas, así como la recopilación de resultados y la confección de síntesis."
      },
      "Operations":{
         "type":"object",
         "title":"Operations",
         "allOf":[
            {
               "$ref":"#/definitions/ListBase"
            },
            {
               "properties":{
                  "operation":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"",
                     "$ref":"#/definitions/Resource"
                  }
               }
            }
         ],
         "description":"Listado de operaciones estadísticas."
      },
      "Producers":{
         "type":"object",
         "title":"Producers",
         "allOf":[
            {
               "$ref":"#/definitions/ListBase"
            },
            {
               "properties":{
                  "producer":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"",
                     "$ref":"#/definitions/Resource"
                  }
               }
            }
         ],
         "description":"Listado de organismos que colaboran en la producción de la estadística."
      },
      "Publishers":{
         "type":"object",
         "title":"Publishers",
         "allOf":[
            {
               "$ref":"#/definitions/ListBase"
            },
            {
               "properties":{
                  "publisher":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"",
                     "$ref":"#/definitions/Resource"
                  }
               }
            }
         ],
         "description":"Listado de organismos que difunden los resultados de la operación estadística."
      },
      "RegionalContributors":{
         "type":"object",
         "title":"RegionalContributors",
         "allOf":[
            {
               "$ref":"#/definitions/ListBase"
            },
            {
               "properties":{
                  "regionalContributor":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"",
                     "$ref":"#/definitions/Resource"
                  }
               }
            }
         ],
         "description":"Organismos regionales colaboradores de la operación."
      },
      "RegionalResponsibles":{
         "type":"object",
         "title":"RegionalResponsibles",
         "allOf":[
            {
               "$ref":"#/definitions/ListBase"
            },
            {
               "properties":{
                  "regionalResponsible":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"",
                     "$ref":"#/definitions/Resource"
                  }
               }
            }
         ],
         "description":"Organismos regionales responsables de la operación."
      },
      "SecondarySubjectAreas":{
         "type":"object",
         "title":"SecondarySubjectAreas",
         "allOf":[
            {
               "$ref":"#/definitions/ListBase"
            },
            {
               "properties":{
                  "secondarySubjectArea":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"",
                     "$ref":"#/definitions/Resource"
                  }
               }
            }
         ],
         "description":"Áreas temáticas secundarias relacionadas con la operación."
      },
      "StatConcDefs":{
         "type":"object",
         "title":"StatConcDefs",
         "allOf":[
            {
               "$ref":"#/definitions/ListBase"
            },
            {
               "properties":{
                  "statConcDef":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"",
                     "$ref":"#/definitions/Resource"
                  }
               }
            }
         ],
         "description":"Listado de conceptos que se manejan en la operación."
      },
      "StatisticalOperationSources":{
         "type":"object",
         "title":"StatisticalOperationSources",
         "allOf":[
            {
               "$ref":"#/definitions/ListBase"
            },
            {
               "properties":{
                  "statisticalOperationSource":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"",
                     "$ref":"#/definitions/Item"
                  }
               }
            }
         ],
         "description":"Fuentes usadas para la elaboración de la operación estadística."
      },
      "StatisticalOperationTypes":{
         "type":"object",
         "title":"StatisticalOperationTypes",
         "allOf":[
            {
               "$ref":"#/definitions/ListBase"
            },
            {
               "properties":{
                  "statisticalOperationType":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"",
                     "$ref":"#/definitions/Item"
                  }
               }
            }
         ],
         "description":"Tipos de operaciones estadísticas."
      },
      "StatisticalUnits":{
         "type":"object",
         "title":"StatisticalUnits",
         "allOf":[
            {
               "$ref":"#/definitions/ListBase"
            },
            {
               "properties":{
                  "statisticalUnit":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"",
                     "$ref":"#/definitions/Resource"
                  }
               }
            }
         ],
         "description":"Unidades básicas de observación estadística para las que se proporcionan los datos."
      },
      "Status":{
         "type":"string",
         "title":"Status",
         "enum":[
            "PLANNING",
            "DESIGN",
            "PRODUCTION",
            "OUT_OF_PRINT"
         ],
         "description":"Estado de la operación estadística."
      },
      "TemporalGranularities":{
         "type":"object",
         "title":"TemporalGranularities",
         "allOf":[
            {
               "$ref":"#/definitions/ListBase"
            },
            {
               "properties":{
                  "temporalGranularity":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"",
                     "$ref":"#/definitions/Resource"
                  }
               }
            }
         ],
         "description":"Granularidades temporales que contemplan los datos de la operación estadística."
      },
      "UpdateFrequencies":{
         "type":"object",
         "title":"UpdateFrequencies",
         "allOf":[
            {
               "$ref":"#/definitions/ListBase"
            },
            {
               "properties":{
                  "updateFrequency":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/statistical-operations/v1.0/domain"
                     },
                     "description":"",
                     "$ref":"#/definitions/Resource"
                  }
               }
            }
         ],
         "description":"Frecuencias de acualización de los datos."
      },
      "ChildLinks":{
         "type":"object",
         "title":"ChildLinks",
         "allOf":[
            {
               "properties":{
                  "total":{
                     "xml":{
                        "attribute":true,
                        "namespace":""
                     },
                     "description":"",
                     "type":"number"
                  },
                  "childLink":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/common/v1.0/domain"
                     },
                     "description":"",
                     "$ref":"#/definitions/ResourceLink"
                  }
               }
            }
         ],
         "description":"Recursos a los que se puede acceder desde el presente recurso."
      },
      "InternationalString":{
         "type":"object",
         "title":"InternationalString",
         "allOf":[
            {
               "properties":{
                  "text":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/common/v1.0/domain"
                     },
                     "description":"",
                     "$ref":"#/definitions/LocalisedString"
                  }
               }
            }
         ],
         "description":"Texto en múltiples lenguajes."
      },
      "Item":{
         "type":"object",
         "title":"Item",
         "allOf":[
            {
               "properties":{
                  "id":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/common/v1.0/domain"
                     },
                     "description":"",
                     "type":"string"
                  },
                  "name":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/common/v1.0/domain"
                     },
                     "description":"",
                     "$ref":"#/definitions/InternationalString"
                  }
               }
            }
         ],
         "description":""
      },
      "ListBase":{
         "type":"object",
         "title":"ListBase",
         "allOf":[
            {
               "properties":{
                  "firstLink":{
                     "xml":{
                        "attribute":true,
                        "namespace":""
                     },
                     "description":"",
                     "type":"string"
                  },
                  "kind":{
                     "xml":{
                        "attribute":true,
                        "namespace":""
                     },
                     "description":"",
                     "type":"string"
                  },
                  "lastLink":{
                     "xml":{
                        "attribute":true,
                        "namespace":""
                     },
                     "description":"",
                     "type":"string"
                  },
                  "limit":{
                     "xml":{
                        "attribute":true,
                        "namespace":""
                     },
                     "description":"",
                     "type":"number"
                  },
                  "nextLink":{
                     "xml":{
                        "attribute":true,
                        "namespace":""
                     },
                     "description":"",
                     "type":"string"
                  },
                  "offset":{
                     "xml":{
                        "attribute":true,
                        "namespace":""
                     },
                     "description":"",
                     "type":"number"
                  },
                  "previousLink":{
                     "xml":{
                        "attribute":true,
                        "namespace":""
                     },
                     "description":"",
                     "type":"string"
                  },
                  "selfLink":{
                     "xml":{
                        "attribute":true,
                        "namespace":""
                     },
                     "description":"",
                     "type":"string"
                  },
                  "total":{
                     "xml":{
                        "attribute":true,
                        "namespace":""
                     },
                     "description":"",
                     "type":"number"
                  }
               }
            }
         ],
         "description":""
      },
      "LocalisedString":{
         "type":"object",
         "title":"LocalisedString",
         "allOf":[
            {
               "properties":{
                  "lang":{
                     "xml":{
                        "attribute":true,
                        "namespace":"http://www.w3.org/XML/1998/namespace"
                     },
                     "description":"",
                     "type":"string"
                  },
                  "(value)":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/common/v1.0/domain"
                     },
                     "description":"",
                     "type":"string"
                  }
               }
            }
         ],
         "description":"Texto en un idioma en particular."
      },
      "Resource":{
         "type":"object",
         "title":"Resource",
         "allOf":[
            {
               "properties":{
                  "kind":{
                     "xml":{
                        "attribute":true,
                        "namespace":""
                     },
                     "description":"",
                     "type":"string"
                  },
                  "id":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/common/v1.0/domain"
                     },
                     "description":"",
                     "type":"string"
                  },
                  "name":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/common/v1.0/domain"
                     },
                     "description":"",
                     "$ref":"#/definitions/InternationalString"
                  },
                  "nestedId":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/common/v1.0/domain"
                     },
                     "description":"",
                     "type":"string"
                  },
                  "selfLink":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/common/v1.0/domain"
                     },
                     "description":"",
                     "$ref":"#/definitions/ResourceLink"
                  },
                  "urn":{
                     "xml":{
                        "namespace":"http://www.siemac.org/metamac/rest/common/v1.0/domain"
                     },
                     "description":"",
                     "type":"string"
                  }
               }
            }
         ],
         "description":""
      },
      "ResourceLink":{
         "type":"object",
         "title":"ResourceLink",
         "allOf":[
            {
               "properties":{
                  "href":{
                     "xml":{
                        "attribute":true,
                        "namespace":""
                     },
                     "description":"",
                     "type":"string"
                  },
                  "kind":{
                     "xml":{
                        "attribute":true,
                        "namespace":""
                     },
                     "description":"",
                     "type":"string"
                  }
               }
            }
         ],
         "description":""
      }
   },
   "paths":{
      "/v1.0/families":{
         "get":{
            "tags":[
               "Familias de operaciones"
            ],
            "description":"Permite obtener el listado de familias de operaciones estadísticas.",
            "operationId":"resource_StatisticalOperationsV1_0_findFamilies_GET",
            "produces":[
               "application/xml"
            ],
            "parameters":[
               {
                  "name":"limit",
                  "in":"query",
                  "type":"string",
                  "description":"Número máximo de resultados a obtener"
               },
               {
                  "name":"offset",
                  "in":"query",
                  "type":"string",
                  "description":"Desplazamiento. Número a partir del cual se comienzan a obtener los resultados."
               },
               {
                  "name":"orderBy",
                  "in":"query",
                  "type":"string",
                  "description":"Permite ordenar la lista de resultados según un determinado metadato. El orden se especifica mediante un metadato y el sentido del orden (operador) que se le quiere aplicar.<br/>\r\n Los posibles operadores son ASC y DESC.<br/>\r\n El metadato que se puede usar es ID. <br/>Ejemplos:<br/>\r\n- ID ASC<br/>\r\n- ID DESC"
               },
               {
                  "name":"query",
                  "in":"query",
                  "type":"string",
                  "description":"Permite realizar una búsqueda sobre los resultados. <br/>\r\n Los metadatos sobre los que se puede buscar son: ID, URN, TITLE, ACRONYM, DESCRIPTION e INVENTORY_DATE.<br/>\r\n Los operadores lógicos que se permite usar son: AND y OR.  <br/>\r\n Los operadores de comparación que se permite usar son: EQ, IEQ, LIKE, ILIKE, NE, LT, LE, GT, GE, IS_NULL, IS_NOT_NULL e IN.  <br/>\r\n Ejemplos: <br/>\r\n- ID LIKE \"E303\" <br/>\r\n- (ID LIKE \"Family1\" AND ACRONYM EQ \"Family1\") OR (DESCRIPTION IS_NOT_NULL)"
               }
            ],
            "responses":{
               "200":{
                  "schema":{
                     "description":"",
                     "$ref":"#/definitions/Families"
                  },
                  "headers":{

                  },
                  "description":"Éxito. Indica que la petición ha sido resuelta correctamente."
               },
               "406":{
                  "description":"No aceptable. El formato solicitado no es válido."
               },
               "500":{
                  "description":"Error interno del servidor. Se ha producido un error que impide que se obtenga el recurso solicitado."
               }
            }
         }
      },
      "/v1.0/families/{id}":{
         "get":{
            "tags":[
               "Familias de operaciones"
            ],
            "description":"Permite obtener una familia en particular.",
            "operationId":"resource_StatisticalOperationsV1_0_retrieveFamilyById_GET",
            "produces":[
               "application/xml"
            ],
            "parameters":[
               {
                  "name":"id",
                  "in":"path",
                  "type":"string",
                  "description":"Identificador de la familia"
               }
            ],
            "responses":{
               "200":{
                  "schema":{
                     "description":"",
                     "$ref":"#/definitions/Family"
                  },
                  "headers":{

                  },
                  "description":"Éxito. Indica que la petición ha sido resuelta correctamente."
               },
               "406":{
                  "description":"No aceptable. El formato solicitado no es válido."
               },
               "500":{
                  "description":"Error interno del servidor. Se ha producido un error que impide que se obtenga el recurso solicitado."
               }
            }
         }
      },
      "/v1.0/families/{id}/operations":{
         "get":{
            "tags":[
               "Familias de operaciones"
            ],
            "description":"Permite obtener todas las operaciones que forman parte de una determina familia.",
            "operationId":"resource_StatisticalOperationsV1_0_findOperationsByFamily_GET",
            "produces":[
               "application/xml"
            ],
            "parameters":[
               {
                  "name":"id",
                  "in":"path",
                  "type":"string",
                  "description":"Identificador de la familia estadística"
               },
               {
                  "name":"limit",
                  "in":"query",
                  "type":"string",
                  "description":"Número máximo de resultados a obtener"
               },
               {
                  "name":"offset",
                  "in":"query",
                  "type":"string",
                  "description":"Desplazamiento. Número a partir del cual se comienzan a obtener los resultados."
               },
               {
                  "name":"orderBy",
                  "in":"query",
                  "type":"string",
                  "description":"Permite ordenar la lista de resultados según un determinado metadato. El orden se especifica mediante un metadato y el sentido del orden (operador) que se le quiere aplicar.<br/>\r\n Los posibles operadores son ASC y DESC.<br/>\r\n El metadato que se puede usar es ID. <br/>Ejemplos:<br/>\r\n- ID ASC<br/>\r\n- ID DESC"
               },
               {
                  "name":"query",
                  "in":"query",
                  "type":"string",
                  "description":"Permite realizar una búsqueda sobre los resultados. <br/>\r\n Los metadatos sobre los que se puede buscar son: ID, URN, TITLE, ACRONYM, SUBJECT_AREA_URN, SECONDARY_SUBJECT_AREA_URN, DESCRIPTION, STATISTICAL_OPERATION_TYPE_ID, OFFICIALITY_TYPE_ID, IS_INDICATORS_SYSTEM, PRODUCER_URN, CURRENTLY_ACTIVE, STATUS, PUBLISHER_URN e INVENTORY_DATE.<br/>\r\n Los operadores lógicos que se permite usar son: AND y OR.  <br/>\r\n Los operadores de comparación que se permite usar son: EQ, IEQ, LIKE, ILIKE, NE, LT, LE, GT, GE, IS_NULL, IS_NOT_NULL e IN.  <br/>\r\n Ejemplos: <br/>\r\n- ID LIKE \"E303\" <br/>\r\n- (ID LIKE \"E303\" AND CONTACT_URN LIKE \"urn:contact:1\") OR (CONTACT_URN EQ \"urn:contact:2\")"
               }
            ],
            "responses":{
               "200":{
                  "schema":{
                     "description":"",
                     "$ref":"#/definitions/Operations"
                  },
                  "headers":{

                  },
                  "description":"Éxito. Indica que la petición ha sido resuelta correctamente."
               },
               "406":{
                  "description":"No aceptable. El formato solicitado no es válido."
               },
               "500":{
                  "description":"Error interno del servidor. Se ha producido un error que impide que se obtenga el recurso solicitado."
               }
            }
         }
      },
      "/v1.0/operations":{
         "get":{
            "tags":[
               "Operaciones estadísticas"
            ],
            "description":"Permite obtener el listado de operaciones estadísticas existentes en el inventario.",
            "operationId":"resource_StatisticalOperationsV1_0_findOperations_GET",
            "produces":[
               "application/xml"
            ],
            "parameters":[
               {
                  "name":"limit",
                  "in":"query",
                  "type":"string",
                  "description":"Número máximo de resultados a obtener"
               },
               {
                  "name":"offset",
                  "in":"query",
                  "type":"string",
                  "description":"Desplazamiento. Número a partir del cual se comienzan a obtener los resultados."
               },
               {
                  "name":"orderBy",
                  "in":"query",
                  "type":"string",
                  "description":"Permite ordenar la lista de resultados según un determinado metadato. El orden se especifica mediante un metadato y el sentido del orden (operador) que se le quiere aplicar.<br/>\r\n Los posibles operadores son ASC y DESC.<br/>\r\n El metadato que se puede usar es ID. <br/>Ejemplos:<br/>\r\n- ID ASC<br/>\r\n- ID DESC"
               },
               {
                  "name":"query",
                  "in":"query",
                  "type":"string",
                  "description":"Permite realizar una búsqueda sobre los resultados. <br/>\r\n Los metadatos sobre los que se puede buscar son: ID, URN, TITLE, ACRONYM, SUBJECT_AREA_URN, SECONDARY_SUBJECT_AREA_URN, DESCRIPTION, STATISTICAL_OPERATION_TYPE_ID, OFFICIALITY_TYPE_ID, IS_INDICATORS_SYSTEM, PRODUCER_URN, CURRENTLY_ACTIVE, STATUS, PUBLISHER_URN e INVENTORY_DATE.<br/>\r\n Los operadores lógicos que se permite usar son: AND y OR.  <br/>\r\n Los operadores de comparación que se permite usar son: EQ, IEQ, LIKE, ILIKE, NE, LT, LE, GT, GE, IS_NULL, IS_NOT_NULL e IN.  <br/>\r\n Ejemplos: <br/>\r\n- ID LIKE \"E303\" <br/>\r\n- (ID LIKE \"E303\" AND CONTACT_URN LIKE \"urn:contact:1\") OR (CONTACT_URN EQ \"urn:contact:2\")"
               }
            ],
            "responses":{
               "200":{
                  "schema":{
                     "description":"",
                     "$ref":"#/definitions/Operations"
                  },
                  "headers":{

                  },
                  "description":"Éxito. Indica que la petición ha sido resuelta correctamente."
               },
               "406":{
                  "description":"No aceptable. El formato solicitado no es válido."
               },
               "500":{
                  "description":"Error interno del servidor. Se ha producido un error que impide que se obtenga el recurso solicitado."
               }
            }
         }
      },
      "/v1.0/operations/{id}":{
         "get":{
            "tags":[
               "Operaciones estadísticas"
            ],
            "description":"Permite obtener una operación estadística en concreto.",
            "operationId":"resource_StatisticalOperationsV1_0_retrieveOperationById_GET",
            "produces":[
               "application/xml"
            ],
            "parameters":[
               {
                  "name":"id",
                  "in":"path",
                  "type":"string",
                  "description":"Identificador de la operación estadística"
               }
            ],
            "responses":{
               "200":{
                  "schema":{
                     "description":"",
                     "$ref":"#/definitions/Operation"
                  },
                  "headers":{

                  },
                  "description":"Éxito. Indica que la petición ha sido resuelta correctamente."
               },
               "406":{
                  "description":"No aceptable. El formato solicitado no es válido."
               },
               "500":{
                  "description":"Error interno del servidor. Se ha producido un error que impide que se obtenga el recurso solicitado."
               }
            }
         }
      },
      "/v1.0/operations/{operationId}/instances":{
         "get":{
            "tags":[
               "Operaciones estadísticas"
            ],
            "description":"Permite obtener el listado de instancias relacionadas con una operación estadística en concreto.",
            "operationId":"resource_StatisticalOperationsV1_0_findInstances_GET",
            "produces":[
               "application/xml"
            ],
            "parameters":[
               {
                  "name":"operationId",
                  "in":"path",
                  "type":"string",
                  "description":"Identificador de la operación."
               },
               {
                  "name":"limit",
                  "in":"query",
                  "type":"string",
                  "description":"Número máximo de resultados a obtener"
               },
               {
                  "name":"offset",
                  "in":"query",
                  "type":"string",
                  "description":"Deplazamiento. Número a partir del cual se comienzan a obtener los resultados."
               },
               {
                  "name":"orderBy",
                  "in":"query",
                  "type":"string",
                  "description":"Permite ordenar la lista de resultados según un determinado metadato. El orden se especifica mediante un metadato y el sentido del orden (operador) que se le quiere aplicar.<br/>\r\n Los posibles operadores son ASC y DESC.<br/>\r\n El metadato que se puede usar es ID. <br/>Ejemplos:<br/>\r\n- ID ASC<br/>\r\n- ID DESC"
               },
               {
                  "name":"query",
                  "in":"query",
                  "type":"string",
                  "description":"Permite realizar una búsqueda sobre los resultados. <br/>\r\n Los metadatos sobre los que se puede buscar son: ID, URN, TITLE, ACRONYM, DATA_DESCRIPTION, GEOGRAPHIC_GRANULARITY_URN, TEMPORAL_GRANULARITY_URN e INVENTORY_DATE.<br/>\r\n Los operadores lógicos que se permite usar son: AND y OR.  <br/>\r\n Los operadores de comparación que se permite usar son: EQ, IEQ, LIKE, ILIKE, NE, LT, LE, GT, GE, IS_NULL, IS_NOT_NULL e IN.  <br/>\r\n Ejemplos: <br/>\r\n- ID LIKE \"E303\" <br/>\r\n- (ID LIKE \"Instance1\" AND DATA_DESCRIPTION EQ \"DataDescription1\") OR (ACRONYM EQ \"Instance1\")"
               }
            ],
            "responses":{
               "200":{
                  "schema":{
                     "description":"",
                     "$ref":"#/definitions/Instances"
                  },
                  "headers":{

                  },
                  "description":"Éxito. Indica que la petición ha sido resuelta correctamente."
               },
               "406":{
                  "description":"No aceptable. El formato solicitado no es válido."
               },
               "500":{
                  "description":"Error interno del servidor. Se ha producido un error que impide que se obtenga el recurso solicitado."
               }
            }
         }
      },
      "/v1.0/operations/{operationId}/instances/{id}":{
         "get":{
            "tags":[
               "Operaciones estadísticas"
            ],
            "description":"Permite obtener una instancia en particular de una operación estadística.",
            "operationId":"resource_StatisticalOperationsV1_0_retrieveInstanceById_GET",
            "produces":[
               "application/xml"
            ],
            "parameters":[
               {
                  "name":"id",
                  "in":"path",
                  "type":"string",
                  "description":"Identificador de la instancia"
               },
               {
                  "name":"operationId",
                  "in":"path",
                  "type":"string",
                  "description":"Identificador de la operación estadística"
               }
            ],
            "responses":{
               "200":{
                  "schema":{
                     "description":"",
                     "$ref":"#/definitions/Instance"
                  },
                  "headers":{

                  },
                  "description":"Éxito. Indica que la petición ha sido resuelta correctamente."
               },
               "406":{
                  "description":"No aceptable. El formato solicitado no es válido."
               },
               "500":{
                  "description":"Error interno del servidor. Se ha producido un error que impide que se obtenga el recurso solicitado."
               }
            }
         }
      },
      "/v1.0/operations/{id}/families":{
         "get":{
            "tags":[
               "Operaciones estadísticas"
            ],
            "description":"Permite obtener el listado de familias estadísticas en las que se engloba una operación en concreto.",
            "operationId":"resource_StatisticalOperationsV1_0_retrieveFamiliesByOperation_GET",
            "produces":[
               "application/xml"
            ],
            "parameters":[
               {
                  "name":"id",
                  "in":"path",
                  "type":"string",
                  "description":"Identificador de la operación estadística"
               }
            ],
            "responses":{
               "200":{
                  "schema":{
                     "description":"",
                     "$ref":"#/definitions/Families"
                  },
                  "headers":{

                  },
                  "description":"Éxito. Indica que la petición ha sido resuelta correctamente."
               },
               "406":{
                  "description":"No aceptable. El formato solicitado no es válido."
               },
               "500":{
                  "description":"Error interno del servidor. Se ha producido un error que impide que se obtenga el recurso solicitado."
               }
            }
         }
      },
      "/v1.0/statisticalOperationSources":{
         "get":{
            "tags":[
               "Tablas de valores auxiliares"
            ],
            "description":"Permite obtener todos los posibles tipos de orígenes de datos disponibles para las operaciones estadísticas.",
            "operationId":"resource_StatisticalOperationsV1_0_retrieveStatisticalOperationSources_GET",
            "produces":[
               "application/xml"
            ],
            "parameters":[

            ],
            "responses":{
               "200":{
                  "schema":{
                     "description":"",
                     "$ref":"#/definitions/StatisticalOperationSources"
                  },
                  "headers":{

                  },
                  "description":"Éxito. Indica que la petición ha sido resuelta correctamente."
               },
               "406":{
                  "description":"No aceptable. El formato solicitado no es válido."
               },
               "500":{
                  "description":"Error interno del servidor. Se ha producido un error que impide que se obtenga el recurso solicitado."
               }
            }
         }
      },
      "/v1.0/officialityTypes":{
         "get":{
            "tags":[
               "Tablas de valores auxiliares"
            ],
            "description":"Permite obtener todos los tipos de oficialidad que se le pueden asignar a las diferentes operaciones estadísticas.",
            "operationId":"resource_StatisticalOperationsV1_0_retrieveOfficialityTypes_GET",
            "produces":[
               "application/xml"
            ],
            "parameters":[

            ],
            "responses":{
               "200":{
                  "schema":{
                     "description":"",
                     "$ref":"#/definitions/OfficialityTypes"
                  },
                  "headers":{

                  },
                  "description":"Éxito. Indica que la petición ha sido resuelta correctamente."
               },
               "406":{
                  "description":"No aceptable. El formato solicitado no es válido."
               },
               "500":{
                  "description":"Error interno del servidor. Se ha producido un error que impide que se obtenga el recurso solicitado."
               }
            }
         }
      },
      "/v1.0/costs":{
         "get":{
            "tags":[
               "Tablas de valores auxiliares"
            ],
            "description":"Permite obtener el listado de todos los tipos de costes disponibles para las operaciones estadísticas.",
            "operationId":"resource_StatisticalOperationsV1_0_retrieveCosts_GET",
            "produces":[
               "application/xml"
            ],
            "parameters":[

            ],
            "responses":{
               "200":{
                  "schema":{
                     "description":"",
                     "$ref":"#/definitions/Costs"
                  },
                  "headers":{

                  },
                  "description":"Éxito. Indica que la petición ha sido resuelta correctamente."
               },
               "406":{
                  "description":"No aceptable. El formato solicitado no es válido."
               },
               "500":{
                  "description":"Error interno del servidor. Se ha producido un error que impide que se obtenga el recurso solicitado."
               }
            }
         }
      },
      "/v1.0/collMethods":{
         "get":{
            "tags":[
               "Tablas de valores auxiliares"
            ],
            "description":"Permite obtener todos los métodos de recolección de datos existentes.",
            "operationId":"resource_StatisticalOperationsV1_0_retrieveCollMethods_GET",
            "produces":[
               "application/xml"
            ],
            "parameters":[

            ],
            "responses":{
               "200":{
                  "schema":{
                     "description":"",
                     "$ref":"#/definitions/CollMethods"
                  },
                  "headers":{

                  },
                  "description":"Éxito. Indica que la petición ha sido resuelta correctamente."
               },
               "406":{
                  "description":"No aceptable. El formato solicitado no es válido."
               },
               "500":{
                  "description":"Error interno del servidor. Se ha producido un error que impide que se obtenga el recurso solicitado."
               }
            }
         }
      },
      "/v1.0/instanceTypes":{
         "get":{
            "tags":[
               "Tablas de valores auxiliares"
            ],
            "description":"Permite obtener todos los tipos de instancias de operaciones que existen.",
            "operationId":"resource_StatisticalOperationsV1_0_retrieveInstanceTypes_GET",
            "produces":[
               "application/xml"
            ],
            "parameters":[

            ],
            "responses":{
               "200":{
                  "schema":{
                     "description":"",
                     "$ref":"#/definitions/InstanceTypes"
                  },
                  "headers":{

                  },
                  "description":"Éxito. Indica que la petición ha sido resuelta correctamente."
               },
               "406":{
                  "description":"No aceptable. El formato solicitado no es válido."
               },
               "500":{
                  "description":"Error interno del servidor. Se ha producido un error que impide que se obtenga el recurso solicitado."
               }
            }
         }
      },
      "/v1.0/statisticalOperationTypes":{
         "get":{
            "tags":[
               "Tablas de valores auxiliares"
            ],
            "description":"Permite obtener todos los tipos de operaciones estadísticas existentes.",
            "operationId":"resource_StatisticalOperationsV1_0_retrieveStatisticalOperationTypes_GET",
            "produces":[
               "application/xml"
            ],
            "parameters":[

            ],
            "responses":{
               "200":{
                  "schema":{
                     "description":"",
                     "$ref":"#/definitions/StatisticalOperationTypes"
                  },
                  "headers":{

                  },
                  "description":"Éxito. Indica que la petición ha sido resuelta correctamente."
               },
               "406":{
                  "description":"No aceptable. El formato solicitado no es válido."
               },
               "500":{
                  "description":"Error interno del servidor. Se ha producido un error que impide que se obtenga el recurso solicitado."
               }
            }
         }
      }
   }
}