ALTER TABLE TB_FAMILIES ALTER COLUMN PROC_STATUS VARCHAR(255) NOT NULL;
ALTER TABLE TB_EXTERNAL_ITEMS ALTER COLUMN MANAGEMENT_APP_URL VARCHAR(4000);
ALTER TABLE TB_EXTERNAL_ITEMS ALTER COLUMN TYPE VARCHAR(255) NOT NULL;
ALTER TABLE TB_OPERATIONS ALTER COLUMN PROC_STATUS VARCHAR(255) NOT NULL;
ALTER TABLE TB_OPERATIONS ALTER COLUMN STATUS VARCHAR(255) NOT NULL;
ALTER TABLE TB_INSTANCES ALTER COLUMN PROC_STATUS VARCHAR(255) NOT NULL;
