-- All these inserts are examples. You have to insert the data that you required

-- SURVEY TYPES

Insert into TB_LIS_SURVEY_TYPES (ID,IDENTIFIER,UUID,VERSION) values (GET_NEXT_SEQUENCE_VALUE('SURVEY_TYPES'),'COYUNTURAL','f5895f76-14ae-47d2-b228-f4e977833be7',0);
UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'SURVEY_TYPES';

Insert into TB_LIS_SURVEY_TYPES (ID,IDENTIFIER,UUID,VERSION) values (GET_NEXT_SEQUENCE_VALUE('SURVEY_TYPES'),'ESTRUCTURAL','aaaaaaaa-14ae-47d2-b228-f4e977833be7',0);
UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'SURVEY_TYPES';

Insert into TB_LIS_SURVEY_TYPES (ID,IDENTIFIER,UUID,VERSION) values (GET_NEXT_SEQUENCE_VALUE('SURVEY_TYPES'),'OTRAS','aaaaaaaa-14ae-47d2-b228-f4e977833be8',0);
UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'SURVEY_TYPES';

-- INSTANCE TYPES

Insert into TB_LIS_INSTANCE_TYPES (ID,IDENTIFIER,UUID,VERSION) values (GET_NEXT_SEQUENCE_VALUE('INSTANCE_TYPES'),'SERIE','bbbbbbbb-14ae-47d2-b228-f4e977833be7',0);
UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'INSTANCE_TYPES';

Insert into TB_LIS_INSTANCE_TYPES (ID,IDENTIFIER,UUID,VERSION) values (GET_NEXT_SEQUENCE_VALUE('INSTANCE_TYPES'),'SECCION','cccccccc-14ae-47d2-b228-f4e977833be7',0);
UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'INSTANCE_TYPES';

-- COLL METHODS

Insert into TB_LIS_COLL_METHODS (ID,IDENTIFIER,UUID,VERSION) values (GET_NEXT_SEQUENCE_VALUE('COLL_METHODS'),'AUTOENUMERACION','1ddddddd-14ae-47d2-b228-f4e977833be7',0);
UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'COLL_METHODS';

Insert into TB_LIS_COLL_METHODS (ID,IDENTIFIER,UUID,VERSION) values (GET_NEXT_SEQUENCE_VALUE('COLL_METHODS'),'ENTREVISTA_DIRECTA','e2eeeeee-14ae-47d2-b228-f4e977833be7',0);
UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'COLL_METHODS';

Insert into TB_LIS_COLL_METHODS (ID,IDENTIFIER,UUID,VERSION) values (GET_NEXT_SEQUENCE_VALUE('COLL_METHODS'),'CONVERSACION_TELEFONO','eee3eeee-14ae-47d2-b228-f4e977833be7',0);
UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'COLL_METHODS';

Insert into TB_LIS_COLL_METHODS (ID,IDENTIFIER,UUID,VERSION) values (GET_NEXT_SEQUENCE_VALUE('COLL_METHODS'),'TRANSCRIPCION_DOCUMENTO','ee4eeeee-14ae-47d2-b228-f4e977833be7',0);
UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'COLL_METHODS';

Insert into TB_LIS_COLL_METHODS (ID,IDENTIFIER,UUID,VERSION) values (GET_NEXT_SEQUENCE_VALUE('COLL_METHODS'),'OBSERVACION_DIRECTA','eeeeee5e-14ae-47d2-b228-f4e977833be7',0);
UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'COLL_METHODS';

Insert into TB_LIS_COLL_METHODS (ID,IDENTIFIER,UUID,VERSION) values (GET_NEXT_SEQUENCE_VALUE('COLL_METHODS'),'FORMAS_MIXTAS','eeeee6ee-14ae-47d2-b228-f4e977833be7',0);
UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'COLL_METHODS';

Insert into TB_LIS_COLL_METHODS (ID,IDENTIFIER,UUID,VERSION) values (GET_NEXT_SEQUENCE_VALUE('COLL_METHODS'),'OTRAS','eeee7eee-14ae-47d2-b228-f4e977833be7',0);
UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'COLL_METHODS';

Insert into TB_LIS_COLL_METHODS (ID,IDENTIFIER,UUID,VERSION) values (GET_NEXT_SEQUENCE_VALUE('COLL_METHODS'),'NO_APLICABLE','ee8eeeee-14ae-47d2-b228-f4e977833be7',0);
UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'COLL_METHODS';

Insert into TB_LIS_COLL_METHODS (ID,IDENTIFIER,UUID,VERSION) values (GET_NEXT_SEQUENCE_VALUE('COLL_METHODS'),'INDETERMINADA','e9eeeeee-14ae-47d2-b228-f4e977833be7',0);
UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'COLL_METHODS';

-- COSTS

Insert into TB_LIS_COSTS (ID,IDENTIFIER,UUID,VERSION) values (GET_NEXT_SEQUENCE_VALUE('COSTS'),'MUY_BAJO','ffffffff-14ae-47d2-b228-f4e977833be7',0);
UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'COSTS';

Insert into TB_LIS_COSTS (ID,IDENTIFIER,UUID,VERSION) values (GET_NEXT_SEQUENCE_VALUE('COSTS'),'BAJO','llllllll-14ae-47d2-b228-f4e977833be7',0);
UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'COSTS';

Insert into TB_LIS_COSTS (ID,IDENTIFIER,UUID,VERSION) values (GET_NEXT_SEQUENCE_VALUE('COSTS'),'MEDIO','mmmmmmmm-14ae-47d2-b228-f4e977833be7',0);
UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'COSTS';

Insert into TB_LIS_COSTS (ID,IDENTIFIER,UUID,VERSION) values (GET_NEXT_SEQUENCE_VALUE('COSTS'),'ALTO','nnnnnnnn-14ae-47d2-b228-f4e977833be7',0);
UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'COSTS';

Insert into TB_LIS_COSTS (ID,IDENTIFIER,UUID,VERSION) values (GET_NEXT_SEQUENCE_VALUE('COSTS'),'MUY_ATO','oooooooo-14ae-47d2-b228-f4e977833be7',0);
UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'COSTS';

-- SURVEY SOURCES

Insert into TB_LIS_SURVEY_SOURCES (ID,IDENTIFIER,UUID,VERSION) values (GET_NEXT_SEQUENCE_VALUE('SURVEY_SOURCES'),'ENCUESTA','hhhhhhhh-14ae-47d2-b228-f4e977833be7',0);
UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'SURVEY_SOURCES';

Insert into TB_LIS_SURVEY_SOURCES (ID,IDENTIFIER,UUID,VERSION) values (GET_NEXT_SEQUENCE_VALUE('SURVEY_SOURCES'),'ADMINISTRACION','iiiiiiii-14ae-47d2-b228-f4e977833be7',0);
UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'SURVEY_SOURCES';

-- OFFICIALITY TYPES

Insert into TB_LIS_OFFICIALITY_TYPES (ID,IDENTIFIER,UUID,VERSION) values (GET_NEXT_SEQUENCE_VALUE('OFFICIALITY_TYPES'),'ESTUDIO','jjjjjjjj-14ae-47d2-b228-f4e977833be7',0);
UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'OFFICIALITY_TYPES';

Insert into TB_LIS_OFFICIALITY_TYPES (ID,IDENTIFIER,UUID,VERSION) values (GET_NEXT_SEQUENCE_VALUE('OFFICIALITY_TYPES'),'OFICIAL','kkkkkkkk-14ae-47d2-b228-f4e977833be7',0);
UPDATE TB_SEQUENCES SET SEQUENCE_NEXT_VALUE = SEQUENCE_NEXT_VALUE + 1 WHERE SEQUENCE_NAME = 'OFFICIALITY_TYPES';

commit;
