-- --------------------------------------------------------------------------------------------------
-- METAMAC-2109 - Problemas actualización desde versión anterior instalada a nueva versión enviada
-- --------------------------------------------------------------------------------------------------


alter table TB_OPERATIONS add (
  SPECIFIC_LEGAL_ACTS_FK NUMBER(19),
  SPECIFIC_DATA_SHARING_FK NUMBER(19)
);

ALTER TABLE TB_OPERATIONS ADD CONSTRAINT FK_TB_OPERATIONS_SPECIFIC_LE58
	FOREIGN KEY (SPECIFIC_LEGAL_ACTS_FK) REFERENCES TB_INTERNATIONAL_STRINGS (ID)
;
ALTER TABLE TB_OPERATIONS ADD CONSTRAINT FK_TB_OPERATIONS_SPECIFIC_DA90
	FOREIGN KEY (SPECIFIC_DATA_SHARING_FK) REFERENCES TB_INTERNATIONAL_STRINGS (ID)
;


alter table tb_instances drop column GEOGRAPHIC_GRANULARITY_FK; 
alter table tb_instances drop column TEMPORAL_GRANULARITY_FK; 


CREATE TABLE TB_EI_GEO_GRANULARITIES (
  GEOGRAPHIC_GRANULARITY_FK NUMBER(19) NOT NULL,
  TB_INSTANCES NUMBER(19) NOT NULL
);

CREATE TABLE TB_EI_TIME_GRANULARITIES (
  TEMPORAL_GRANULARITY_FK NUMBER(19) NOT NULL,
  TB_INSTANCES NUMBER(19) NOT NULL
);


ALTER TABLE TB_EI_GEO_GRANULARITIES ADD CONSTRAINT PK_TB_EI_GEO_GRANULARITIES
	PRIMARY KEY (GEOGRAPHIC_GRANULARITY_FK, TB_INSTANCES)
;

ALTER TABLE TB_EI_GEO_GRANULARITIES ADD CONSTRAINT FK_TB_EI_GEO_GRANULARITIES_G07
	FOREIGN KEY (GEOGRAPHIC_GRANULARITY_FK) REFERENCES TB_EXTERNAL_ITEMS (ID)
;
ALTER TABLE TB_EI_GEO_GRANULARITIES ADD CONSTRAINT FK_TB_EI_GEO_GRANULARITIES_T52
	FOREIGN KEY (TB_INSTANCES) REFERENCES TB_INSTANCES (ID)
;


ALTER TABLE TB_EI_TIME_GRANULARITIES ADD CONSTRAINT PK_TB_EI_TIME_GRANULARITIES
	PRIMARY KEY (TEMPORAL_GRANULARITY_FK, TB_INSTANCES)
;
ALTER TABLE TB_EI_TIME_GRANULARITIES ADD CONSTRAINT FK_TB_EI_TIME_GRANULARITIES_12
	FOREIGN KEY (TEMPORAL_GRANULARITY_FK) REFERENCES TB_EXTERNAL_ITEMS (ID)
;
ALTER TABLE TB_EI_TIME_GRANULARITIES ADD CONSTRAINT FK_TB_EI_TIME_GRANULARITIES_40
	FOREIGN KEY (TB_INSTANCES) REFERENCES TB_INSTANCES (ID)
;
