-- ###########################################
-- # Drop
-- ###########################################


-- Disable Foreign key constraints
    

  
  
ALTER TABLE TB_LIS_COLL_METHODS DROP CONSTRAINT FK_TB_LIS_COLL_METHODS_DESCRIPTION;

  
ALTER TABLE TB_LIS_COSTS DROP CONSTRAINT FK_TB_LIS_COSTS_DESCRIPTION;

  
ALTER TABLE TB_FAMILIES DROP CONSTRAINT FK_TB_FAMILIES_TITLE_FK;
ALTER TABLE TB_FAMILIES DROP CONSTRAINT FK_TB_FAMILIES_ACRONYM_FK;
ALTER TABLE TB_FAMILIES DROP CONSTRAINT FK_TB_FAMILIES_DESCRIPTION_FK;

  
ALTER TABLE TB_EXTERNAL_ITEMS DROP CONSTRAINT FK_TB_EXTERNAL_ITEMS_TITLE_FK;

  
ALTER TABLE TB_LIS_SURVEY_TYPES DROP CONSTRAINT FK_TB_LIS_SURVEY_TYPES_DESCRIPTION;

  
ALTER TABLE TB_LIS_OFFICIALITY_TYPES DROP CONSTRAINT FK_TB_LIS_OFFICIALITY_TYPES_DESCRIPTION;

  
ALTER TABLE TB_OPERATIONS DROP CONSTRAINT FK_TB_OPERATIONS_COMMON_METADATA_FK;
ALTER TABLE TB_OPERATIONS DROP CONSTRAINT FK_TB_OPERATIONS_TITLE_FK;
ALTER TABLE TB_OPERATIONS DROP CONSTRAINT FK_TB_OPERATIONS_ACRONYM_FK;
ALTER TABLE TB_OPERATIONS DROP CONSTRAINT FK_TB_OPERATIONS_SUBJECT_AREA_FK;
ALTER TABLE TB_OPERATIONS DROP CONSTRAINT FK_TB_OPERATIONS_OBJECTIVE_FK;
ALTER TABLE TB_OPERATIONS DROP CONSTRAINT FK_TB_OPERATIONS_DESCRIPTION_FK;
ALTER TABLE TB_OPERATIONS DROP CONSTRAINT FK_TB_OPERATIONS_SURVEY_TYPE_FK;
ALTER TABLE TB_OPERATIONS DROP CONSTRAINT FK_TB_OPERATIONS_OFFICIALITY_TYPE_FK;
ALTER TABLE TB_OPERATIONS DROP CONSTRAINT FK_TB_OPERATIONS_REL_POL_US_AC_FK;
ALTER TABLE TB_OPERATIONS DROP CONSTRAINT FK_TB_OPERATIONS_REV_POLICY_FK;
ALTER TABLE TB_OPERATIONS DROP CONSTRAINT FK_TB_OPERATIONS_REV_PRACTICE_FK;
ALTER TABLE TB_OPERATIONS DROP CONSTRAINT FK_TB_OPERATIONS_SPECIFIC_LEGAL_ACTS_FK;
ALTER TABLE TB_OPERATIONS DROP CONSTRAINT FK_TB_OPERATIONS_SPECIFIC_DATA_SHARING_FK;
ALTER TABLE TB_OPERATIONS DROP CONSTRAINT FK_TB_OPERATIONS_COMMENT_FK;
ALTER TABLE TB_OPERATIONS DROP CONSTRAINT FK_TB_OPERATIONS_NOTES_FK;

  
ALTER TABLE TB_LIS_INSTANCE_TYPES DROP CONSTRAINT FK_TB_LIS_INSTANCE_TYPES_DESCRIPTION;

  
ALTER TABLE TB_LIS_SURVEY_SOURCES DROP CONSTRAINT FK_TB_LIS_SURVEY_SOURCES_DESCRIPTION;

  
ALTER TABLE TB_INSTANCES DROP CONSTRAINT FK_TB_INSTANCES_TITLE_FK;
ALTER TABLE TB_INSTANCES DROP CONSTRAINT FK_TB_INSTANCES_ACRONYM_FK;
ALTER TABLE TB_INSTANCES DROP CONSTRAINT FK_TB_INSTANCES_OPERATION_FK;
ALTER TABLE TB_INSTANCES DROP CONSTRAINT FK_TB_INSTANCES_DATA_DESCRIPTION_FK;
ALTER TABLE TB_INSTANCES DROP CONSTRAINT FK_TB_INSTANCES_STATISTICAL_POPULATION_FK;
ALTER TABLE TB_INSTANCES DROP CONSTRAINT FK_TB_INSTANCES_GEOGRAPHIC_COMPARABILITY_FK;
ALTER TABLE TB_INSTANCES DROP CONSTRAINT FK_TB_INSTANCES_TEMPORAL_COMPARABILITY_FK;
ALTER TABLE TB_INSTANCES DROP CONSTRAINT FK_TB_INSTANCES_STAT_CONC_DEF_FK;
ALTER TABLE TB_INSTANCES DROP CONSTRAINT FK_TB_INSTANCES_CLASS_SYSTEM_FK;
ALTER TABLE TB_INSTANCES DROP CONSTRAINT FK_TB_INSTANCES_INSTANCE_TYPE_FK;
ALTER TABLE TB_INSTANCES DROP CONSTRAINT FK_TB_INSTANCES_DOC_METHOD_FK;
ALTER TABLE TB_INSTANCES DROP CONSTRAINT FK_TB_INSTANCES_SURVEY_SOURCE_FK;
ALTER TABLE TB_INSTANCES DROP CONSTRAINT FK_TB_INSTANCES_COLL_METHOD_FK;
ALTER TABLE TB_INSTANCES DROP CONSTRAINT FK_TB_INSTANCES_DATA_VALIDATION_FK;
ALTER TABLE TB_INSTANCES DROP CONSTRAINT FK_TB_INSTANCES_DATA_COMPILATION_FK;
ALTER TABLE TB_INSTANCES DROP CONSTRAINT FK_TB_INSTANCES_ADJUSTMENT_FK;
ALTER TABLE TB_INSTANCES DROP CONSTRAINT FK_TB_INSTANCES_COST_BURDEN_FK;
ALTER TABLE TB_INSTANCES DROP CONSTRAINT FK_TB_INSTANCES_QUALITY_DOC_FK;
ALTER TABLE TB_INSTANCES DROP CONSTRAINT FK_TB_INSTANCES_QUALITY_ASSURE_FK;
ALTER TABLE TB_INSTANCES DROP CONSTRAINT FK_TB_INSTANCES_QUALITY_ASSMNT_FK;
ALTER TABLE TB_INSTANCES DROP CONSTRAINT FK_TB_INSTANCES_USER_NEEDS_FK;
ALTER TABLE TB_INSTANCES DROP CONSTRAINT FK_TB_INSTANCES_USER_SAT_FK;
ALTER TABLE TB_INSTANCES DROP CONSTRAINT FK_TB_INSTANCES_COMPLETENESS_FK;
ALTER TABLE TB_INSTANCES DROP CONSTRAINT FK_TB_INSTANCES_TIMELINESS_FK;
ALTER TABLE TB_INSTANCES DROP CONSTRAINT FK_TB_INSTANCES_PUNCTUALITY_FK;
ALTER TABLE TB_INSTANCES DROP CONSTRAINT FK_TB_INSTANCES_ACCURACY_OVERALL_FK;
ALTER TABLE TB_INSTANCES DROP CONSTRAINT FK_TB_INSTANCES_SAMPLING_ERR_FK;
ALTER TABLE TB_INSTANCES DROP CONSTRAINT FK_TB_INSTANCES_NONSAMPLING_ERR_FK;
ALTER TABLE TB_INSTANCES DROP CONSTRAINT FK_TB_INSTANCES_COHER_X_DOMAIN_FK;
ALTER TABLE TB_INSTANCES DROP CONSTRAINT FK_TB_INSTANCES_COHER_INTERNAL_FK;
ALTER TABLE TB_INSTANCES DROP CONSTRAINT FK_TB_INSTANCES_COMMENT_FK;
ALTER TABLE TB_INSTANCES DROP CONSTRAINT FK_TB_INSTANCES_NOTES_FK;

  
ALTER TABLE TB_LOCALISED_STRINGS DROP CONSTRAINT FK_TB_LOCALISED_STRINGS_INTERNATIONAL_STRING_FK;

  

ALTER TABLE TB_EI_CLASS_SYSTEM_LISTS DROP CONSTRAINT FK_TB_EI_CLASS_SYSTEM_LISTS_CLASS_SYSTEM_LIST_FK;
ALTER TABLE TB_EI_CLASS_SYSTEM_LISTS DROP CONSTRAINT FK_TB_EI_CLASS_SYSTEM_LISTS_TB_INSTANCES;

  
ALTER TABLE TB_EI_CONC_DEF_LISTS DROP CONSTRAINT FK_TB_EI_CONC_DEF_LISTS_STAT_CONC_DEF_LIST_FK;
ALTER TABLE TB_EI_CONC_DEF_LISTS DROP CONSTRAINT FK_TB_EI_CONC_DEF_LISTS_TB_INSTANCES;

  
ALTER TABLE TB_EI_FREQ_COLL DROP CONSTRAINT FK_TB_EI_FREQ_COLL_FREQ_COLL_FK;
ALTER TABLE TB_EI_FREQ_COLL DROP CONSTRAINT FK_TB_EI_FREQ_COLL_TB_INSTANCES;

  
ALTER TABLE TB_EI_GEO_GRANULARITIES DROP CONSTRAINT FK_TB_EI_GEO_GRANULARITIES_GEOGRAPHIC_GRANULARITY_FK;
ALTER TABLE TB_EI_GEO_GRANULARITIES DROP CONSTRAINT FK_TB_EI_GEO_GRANULARITIES_TB_INSTANCES;

  
ALTER TABLE TB_EI_INF_SUPPLIERS DROP CONSTRAINT FK_TB_EI_INF_SUPPLIERS_INFORMATION_SUPPLIERS_FK;
ALTER TABLE TB_EI_INF_SUPPLIERS DROP CONSTRAINT FK_TB_EI_INF_SUPPLIERS_TB_INSTANCES;

  
ALTER TABLE TB_EI_PRODUCERS DROP CONSTRAINT FK_TB_EI_PRODUCERS_PRODUCER_FK;
ALTER TABLE TB_EI_PRODUCERS DROP CONSTRAINT FK_TB_EI_PRODUCERS_TB_OPERATIONS;

  
ALTER TABLE TB_EI_PUBLISHERS DROP CONSTRAINT FK_TB_EI_PUBLISHERS_PUBLISHER_FK;
ALTER TABLE TB_EI_PUBLISHERS DROP CONSTRAINT FK_TB_EI_PUBLISHERS_TB_OPERATIONS;

  
ALTER TABLE TB_EI_REG_CONTRIBUTORS DROP CONSTRAINT FK_TB_EI_REG_CONTRIBUTORS_REGIONAL_CONTRIBUTOR_FK;
ALTER TABLE TB_EI_REG_CONTRIBUTORS DROP CONSTRAINT FK_TB_EI_REG_CONTRIBUTORS_TB_OPERATIONS;

  
ALTER TABLE TB_EI_REG_RESPONSIBLES DROP CONSTRAINT FK_TB_EI_REG_RESPONSIBLES_REGIONAL_RESPONSIBLE_FK;
ALTER TABLE TB_EI_REG_RESPONSIBLES DROP CONSTRAINT FK_TB_EI_REG_RESPONSIBLES_TB_OPERATIONS;

  
ALTER TABLE TB_EI_SECONDARY_AREAS DROP CONSTRAINT FK_TB_EI_SECONDARY_AREAS_SECUN_SUBJECT_AREAS_FK;
ALTER TABLE TB_EI_SECONDARY_AREAS DROP CONSTRAINT FK_TB_EI_SECONDARY_AREAS_TB_OPERATIONS;

  
ALTER TABLE TB_EI_STATISTICAL_UNITS DROP CONSTRAINT FK_TB_EI_STATISTICAL_UNITS_STATISTICAL_UNIT_FK;
ALTER TABLE TB_EI_STATISTICAL_UNITS DROP CONSTRAINT FK_TB_EI_STATISTICAL_UNITS_TB_INSTANCES;

  
ALTER TABLE TB_EI_TIME_GRANULARITIES DROP CONSTRAINT FK_TB_EI_TIME_GRANULARITIES_TEMPORAL_GRANULARITY_FK;
ALTER TABLE TB_EI_TIME_GRANULARITIES DROP CONSTRAINT FK_TB_EI_TIME_GRANULARITIES_TB_INSTANCES;

  
ALTER TABLE TB_EI_UNITS_MEASURE DROP CONSTRAINT FK_TB_EI_UNITS_MEASURE_UNIT_MEASURE_FK;
ALTER TABLE TB_EI_UNITS_MEASURE DROP CONSTRAINT FK_TB_EI_UNITS_MEASURE_TB_INSTANCES;

  
ALTER TABLE TB_EI_UPDATE_FREQUENCY DROP CONSTRAINT FK_TB_EI_UPDATE_FREQUENCY_UPDATE_FREQUENCY_FK;
ALTER TABLE TB_EI_UPDATE_FREQUENCY DROP CONSTRAINT FK_TB_EI_UPDATE_FREQUENCY_TB_OPERATIONS;

  
ALTER TABLE TB_FAMILIES_OPERATIONS DROP CONSTRAINT FK_TB_FAMILIES_OPERATIONS_OPERATION;
ALTER TABLE TB_FAMILIES_OPERATIONS DROP CONSTRAINT FK_TB_FAMILIES_OPERATIONS_FAMILY;

  
ALTER TABLE TB_INSTANCES_COSTS DROP CONSTRAINT FK_TB_INSTANCES_COSTS_COST_FK;
ALTER TABLE TB_INSTANCES_COSTS DROP CONSTRAINT FK_TB_INSTANCES_COSTS_TB_INSTANCES;

  

    
-- Drop many to many relations
    
DROP TABLE TB_INSTANCES_COSTS;

DROP TABLE TB_FAMILIES_OPERATIONS;

DROP TABLE TB_EI_UPDATE_FREQUENCY;

DROP TABLE TB_EI_UNITS_MEASURE;

DROP TABLE TB_EI_TIME_GRANULARITIES;

DROP TABLE TB_EI_STATISTICAL_UNITS;

DROP TABLE TB_EI_SECONDARY_AREAS;

DROP TABLE TB_EI_REG_RESPONSIBLES;

DROP TABLE TB_EI_REG_CONTRIBUTORS;

DROP TABLE TB_EI_PUBLISHERS;

DROP TABLE TB_EI_PRODUCERS;

DROP TABLE TB_EI_INF_SUPPLIERS;

DROP TABLE TB_EI_GEO_GRANULARITIES;

DROP TABLE TB_EI_FREQ_COLL;

DROP TABLE TB_EI_CONC_DEF_LISTS;

DROP TABLE TB_EI_CLASS_SYSTEM_LISTS;

-- Drop normal entities
    
DROP TABLE TB_LOCALISED_STRINGS;

DROP TABLE TB_INSTANCES;

DROP TABLE TB_LIS_SURVEY_SOURCES;

DROP TABLE TB_LIS_INSTANCE_TYPES;

DROP TABLE TB_OPERATIONS;

DROP TABLE TB_LIS_OFFICIALITY_TYPES;

DROP TABLE TB_LIS_SURVEY_TYPES;

DROP TABLE TB_EXTERNAL_ITEMS;

DROP TABLE TB_FAMILIES;

DROP TABLE TB_LIS_COSTS;

DROP TABLE TB_LIS_COLL_METHODS;

DROP TABLE TB_INTERNATIONAL_STRINGS;
