-- Delete from TB_OPERATIONS
ALTER TABLE TB_OPERATIONS DROP COLUMN REL_POL_US_AC_URL;
ALTER TABLE TB_OPERATIONS DROP COLUMN REV_POLICY_URL;
ALTER TABLE TB_OPERATIONS DROP COLUMN REV_PRACTICE_URL;
ALTER TABLE TB_OPERATIONS DROP COLUMN COMMENT_URL;
ALTER TABLE TB_OPERATIONS DROP COLUMN NOTES_URL;

-- Delete from TB_INSTANCES
ALTER TABLE TB_INSTANCES DROP COLUMN DOC_METHOD_URL;
ALTER TABLE TB_INSTANCES DROP COLUMN DATA_VALIDATION_URL;
ALTER TABLE TB_INSTANCES DROP COLUMN DATA_COMPILATION_URL;
ALTER TABLE TB_INSTANCES DROP COLUMN ADJUSTMENT_URL;
ALTER TABLE TB_INSTANCES DROP COLUMN COST_BURDEN_URL;
ALTER TABLE TB_INSTANCES DROP COLUMN QUALITY_DOC_URL;
ALTER TABLE TB_INSTANCES DROP COLUMN QUALITY_ASSURE_URL;
ALTER TABLE TB_INSTANCES DROP COLUMN QUALITY_ASSMNT_URL;

ALTER TABLE TB_INSTANCES DROP COLUMN USER_NEEDS_URL;
ALTER TABLE TB_INSTANCES DROP COLUMN USER_SAT_URL;
ALTER TABLE TB_INSTANCES DROP COLUMN COMPLETENESS_URL;
ALTER TABLE TB_INSTANCES DROP COLUMN TIMELINESS_URL;
ALTER TABLE TB_INSTANCES DROP COLUMN PUNCTUALITY_URL;
ALTER TABLE TB_INSTANCES DROP COLUMN ACCURACY_OVERALL_URL;
ALTER TABLE TB_INSTANCES DROP COLUMN SAMPLING_ERR_URL;
ALTER TABLE TB_INSTANCES DROP COLUMN NONSAMPLING_ERR_URL;
ALTER TABLE TB_INSTANCES DROP COLUMN COHER_X_DOMAIN_URL;
ALTER TABLE TB_INSTANCES DROP COLUMN COHER_INTERNAL_URL;
ALTER TABLE TB_INSTANCES DROP COLUMN COMMENT_URL;
ALTER TABLE TB_INSTANCES DROP COLUMN NOTES_URL;